
// This file has been generated by the GUI designer. Do not modify.
namespace Picturez
{
	public partial class ConvertWidget
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Action openAction;
		private global::Gtk.VBox vbox1;
		private global::Gtk.EventBox eventboxToolbar;
		private global::Gtk.HBox hboxToolbarButtons;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Frame frameImageList;
		private global::Gtk.Alignment AlignmentImageList;
		private global::Gtk.ScrolledWindow scrolledWinImageList;
		private global::Gtk.EventBox eventboxImageList;
		private global::Gtk.VBox vboxImageList;
		private global::Gtk.Label GtkLabel29;
		private global::Gtk.VBox vbox2;
		private global::Gtk.Frame frameImageFormat;
		private global::Gtk.Alignment GtkAlignment;
		private global::Gtk.VBox VBoxImageFormat;
		private global::Gtk.Frame frame3;
		private global::Gtk.Alignment GtkAlignment4;
		private global::Gtk.VBox vbox3;
		private global::Gtk.HBox hbox2;
		private global::Gtk.RadioButton rdJpeg;
		private global::Gtk.Label lbQuality;
		private global::Gtk.HScale hscaleQuality;
		private global::Gtk.RadioButton rdJpegGray;
		private global::Gtk.Label GtkLabel6;
		private global::Gtk.Frame frame4;
		private global::Gtk.Alignment GtkAlignment5;
		private global::Gtk.VBox vbox4;
		private global::Gtk.RadioButton rdPng1bit;
		private global::Gtk.RadioButton rdPng8Bit;
		private global::Gtk.RadioButton rdPng24Bit;
		private global::Gtk.HBox hbox5;
		private global::Gtk.RadioButton rdPNG32bit;
		private global::Gtk.Label lbTransparencyColor;
		private global::Gtk.ColorButton btnColor;
		private global::Gtk.RadioButton rdPng32BitAlphaAsValue;
		private global::Gtk.Label GtkLabel11;
		private global::Gtk.Frame frame5;
		private global::Gtk.Alignment GtkAlignment6;
		private global::Gtk.VBox vbox5;
		private global::Gtk.RadioButton rdBmp1bit;
		private global::Gtk.RadioButton rdBmp8bit;
		private global::Gtk.RadioButton rdBmp24bit;
		private global::Gtk.Label GtkLabel15;
		private global::Gtk.Frame frame6;
		private global::Gtk.Alignment GtkAlignment7;
		private global::Gtk.VBox vbox7;
		private global::Gtk.RadioButton rdTiff;
		private global::Gtk.RadioButton rdGif;
		private global::Gtk.RadioButton rdWmf;
		private global::Gtk.RadioButton rdEmf;
		private global::Gtk.RadioButton rdIcon;
		private global::Gtk.Label GtkLabel21;
		private global::Gtk.Label lbFrameImageFormat;
		private global::Gtk.Frame frameImageResize;
		private global::Gtk.Alignment GtkAlignment8;
		private global::Gtk.VBox vbox6;
		private global::Gtk.Frame frame7;
		private global::Gtk.Alignment GtkAlignment9;
		private global::Gtk.RadioButton rdOriginalSize;
		private global::Gtk.Label GtkLabel24;
		private global::Gtk.Frame frame8;
		private global::Gtk.Alignment GtkAlignment10;
		private global::Gtk.VBox vbox9;
		private global::Gtk.RadioButton rdBiggerLength;
		private global::Gtk.HBox hbox7;
		private global::Gtk.Fixed fixed4;
		private global::Gtk.Entry entryBiggerLength;
		private global::Gtk.Label lbPixel_BiggerLength;
		private global::Gtk.Label GtkLabel26;
		private global::Gtk.Frame frame9;
		private global::Gtk.Alignment GtkAlignment11;
		private global::Gtk.VBox vbox8;
		private global::Gtk.RadioButton rdFixSize;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Fixed fixed1;
		private global::Gtk.CheckButton checkBtnStretch;
		private global::Gtk.HBox hbox6;
		private global::Gtk.Fixed fixed3;
		private global::Gtk.Entry entryFixSizeWidth;
		private global::Gtk.Label lbX;
		private global::Gtk.Entry entryFixSizeHeight;
		private global::Gtk.Label lbPixel_FixSize;
		private global::Gtk.Label GtkLabel30;
		private global::Gtk.Label lbFrameImageResize;
		private global::Gtk.Frame frameOutputDirectory;
		private global::Gtk.Alignment GtkAlignment12;
		private global::Gtk.VBox vboxOutputDirectory;
		private global::Picturez.HyperTextLabel htlbOutputDirectory;
		private global::Gtk.CheckButton checkBtnUseOriginalDirectory;
		private global::Gtk.CheckButton checkBtnOverwriteOriginalImage;
		private global::Gtk.Label lbFrameOutputDirectory;
		private global::Gtk.ProgressBar progressbar1;
		private global::Picturez.PicturezButton btnConvert;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Picturez.ConvertWidget
			Stetic.BinContainer w1 = global::Stetic.BinContainer.Attach (this);
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w2 = new global::Gtk.ActionGroup ("Default");
			this.openAction = new global::Gtk.Action ("openAction", null, null, "gtk-open");
			w2.Add (this.openAction, null);
			this.UIManager.InsertActionGroup (w2, 0);
			this.Name = "Picturez.ConvertWidget";
			// Container child Picturez.ConvertWidget.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.eventboxToolbar = new global::Gtk.EventBox ();
			this.eventboxToolbar.Name = "eventboxToolbar";
			// Container child eventboxToolbar.Gtk.Container+ContainerChild
			this.hboxToolbarButtons = new global::Gtk.HBox ();
			this.hboxToolbarButtons.Name = "hboxToolbarButtons";
			this.hboxToolbarButtons.Spacing = 6;
			this.eventboxToolbar.Add (this.hboxToolbarButtons);
			this.vbox1.Add (this.eventboxToolbar);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.eventboxToolbar]));
			w4.Position = 0;
			w4.Expand = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Homogeneous = true;
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.frameImageList = new global::Gtk.Frame ();
			this.frameImageList.WidthRequest = 200;
			this.frameImageList.Name = "frameImageList";
			this.frameImageList.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frameImageList.Gtk.Container+ContainerChild
			this.AlignmentImageList = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.AlignmentImageList.Name = "AlignmentImageList";
			this.AlignmentImageList.LeftPadding = ((uint)(12));
			// Container child AlignmentImageList.Gtk.Container+ContainerChild
			this.scrolledWinImageList = new global::Gtk.ScrolledWindow ();
			this.scrolledWinImageList.CanFocus = true;
			this.scrolledWinImageList.Name = "scrolledWinImageList";
			this.scrolledWinImageList.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledWinImageList.Gtk.Container+ContainerChild
			global::Gtk.Viewport w5 = new global::Gtk.Viewport ();
			w5.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.eventboxImageList = new global::Gtk.EventBox ();
			this.eventboxImageList.Name = "eventboxImageList";
			// Container child eventboxImageList.Gtk.Container+ContainerChild
			this.vboxImageList = new global::Gtk.VBox ();
			this.vboxImageList.Name = "vboxImageList";
			this.vboxImageList.Spacing = 6;
			this.eventboxImageList.Add (this.vboxImageList);
			w5.Add (this.eventboxImageList);
			this.scrolledWinImageList.Add (w5);
			this.AlignmentImageList.Add (this.scrolledWinImageList);
			this.frameImageList.Add (this.AlignmentImageList);
			this.GtkLabel29 = new global::Gtk.Label ();
			this.GtkLabel29.Name = "GtkLabel29";
			this.GtkLabel29.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Image List</b>");
			this.GtkLabel29.UseMarkup = true;
			this.frameImageList.LabelWidget = this.GtkLabel29;
			this.hbox1.Add (this.frameImageList);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.frameImageList]));
			w11.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.frameImageFormat = new global::Gtk.Frame ();
			this.frameImageFormat.Name = "frameImageFormat";
			this.frameImageFormat.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frameImageFormat.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.VBoxImageFormat = new global::Gtk.VBox ();
			this.VBoxImageFormat.Name = "VBoxImageFormat";
			this.VBoxImageFormat.BorderWidth = ((uint)(2));
			// Container child VBoxImageFormat.Gtk.Box+BoxChild
			this.frame3 = new global::Gtk.Frame ();
			this.frame3.Name = "frame3";
			this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame3.Gtk.Container+ContainerChild
			this.GtkAlignment4 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment4.Name = "GtkAlignment4";
			this.GtkAlignment4.LeftPadding = ((uint)(12));
			// Container child GtkAlignment4.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.rdJpeg = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("JPEG"));
			this.rdJpeg.CanFocus = true;
			this.rdJpeg.Name = "rdJpeg";
			this.rdJpeg.DrawIndicator = true;
			this.rdJpeg.UseUnderline = true;
			this.rdJpeg.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.hbox2.Add (this.rdJpeg);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.rdJpeg]));
			w12.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.lbQuality = new global::Gtk.Label ();
			this.lbQuality.Name = "lbQuality";
			this.lbQuality.LabelProp = global::Mono.Unix.Catalog.GetString ("Quality");
			this.hbox2.Add (this.lbQuality);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.lbQuality]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.hscaleQuality = new global::Gtk.HScale (null);
			this.hscaleQuality.CanFocus = true;
			this.hscaleQuality.Name = "hscaleQuality";
			this.hscaleQuality.Adjustment.Lower = 1;
			this.hscaleQuality.Adjustment.Upper = 100;
			this.hscaleQuality.Adjustment.PageIncrement = 10;
			this.hscaleQuality.Adjustment.StepIncrement = 1;
			this.hscaleQuality.Adjustment.Value = 90;
			this.hscaleQuality.DrawValue = true;
			this.hscaleQuality.Digits = 0;
			this.hscaleQuality.ValuePos = ((global::Gtk.PositionType)(2));
			this.hbox2.Add (this.hscaleQuality);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.hscaleQuality]));
			w14.Position = 2;
			this.vbox3.Add (this.hbox2);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox2]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.rdJpegGray = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("JPEG (grayscale)"));
			this.rdJpegGray.Sensitive = false;
			this.rdJpegGray.CanFocus = true;
			this.rdJpegGray.Name = "rdJpegGray";
			this.rdJpegGray.DrawIndicator = true;
			this.rdJpegGray.UseUnderline = true;
			this.rdJpegGray.Group = this.rdJpeg.Group;
			this.vbox3.Add (this.rdJpegGray);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.rdJpegGray]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			this.GtkAlignment4.Add (this.vbox3);
			this.frame3.Add (this.GtkAlignment4);
			this.GtkLabel6 = new global::Gtk.Label ();
			this.GtkLabel6.Name = "GtkLabel6";
			this.GtkLabel6.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>JPEG</b>");
			this.GtkLabel6.UseMarkup = true;
			this.frame3.LabelWidget = this.GtkLabel6;
			this.VBoxImageFormat.Add (this.frame3);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.VBoxImageFormat [this.frame3]));
			w19.Position = 0;
			w19.Expand = false;
			w19.Fill = false;
			// Container child VBoxImageFormat.Gtk.Box+BoxChild
			this.frame4 = new global::Gtk.Frame ();
			this.frame4.Name = "frame4";
			this.frame4.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame4.Gtk.Container+ContainerChild
			this.GtkAlignment5 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment5.Name = "GtkAlignment5";
			this.GtkAlignment5.LeftPadding = ((uint)(12));
			// Container child GtkAlignment5.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.rdPng1bit = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("1 Bit PNG blackwhite"));
			this.rdPng1bit.Sensitive = false;
			this.rdPng1bit.CanFocus = true;
			this.rdPng1bit.Name = "rdPng1bit";
			this.rdPng1bit.DrawIndicator = true;
			this.rdPng1bit.UseUnderline = true;
			this.rdPng1bit.Group = this.rdJpeg.Group;
			this.vbox4.Add (this.rdPng1bit);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.rdPng1bit]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.rdPng8Bit = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("8 Bit PNG grayscale"));
			this.rdPng8Bit.CanFocus = true;
			this.rdPng8Bit.Name = "rdPng8Bit";
			this.rdPng8Bit.DrawIndicator = true;
			this.rdPng8Bit.UseUnderline = true;
			this.rdPng8Bit.Group = this.rdJpeg.Group;
			this.vbox4.Add (this.rdPng8Bit);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.rdPng8Bit]));
			w21.Position = 1;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.rdPng24Bit = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("24 Bit PNG"));
			this.rdPng24Bit.CanFocus = true;
			this.rdPng24Bit.Name = "rdPng24Bit";
			this.rdPng24Bit.DrawIndicator = true;
			this.rdPng24Bit.UseUnderline = true;
			this.rdPng24Bit.Group = this.rdJpeg.Group;
			this.vbox4.Add (this.rdPng24Bit);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.rdPng24Bit]));
			w22.Position = 2;
			w22.Expand = false;
			w22.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.rdPNG32bit = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("32 Bit PNG with transparency"));
			this.rdPNG32bit.CanFocus = true;
			this.rdPNG32bit.Name = "rdPNG32bit";
			this.rdPNG32bit.DrawIndicator = true;
			this.rdPNG32bit.UseUnderline = true;
			this.rdPNG32bit.Group = this.rdJpeg.Group;
			this.hbox5.Add (this.rdPNG32bit);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.rdPNG32bit]));
			w23.Position = 0;
			// Container child hbox5.Gtk.Box+BoxChild
			this.lbTransparencyColor = new global::Gtk.Label ();
			this.lbTransparencyColor.Sensitive = false;
			this.lbTransparencyColor.Name = "lbTransparencyColor";
			this.lbTransparencyColor.LabelProp = global::Mono.Unix.Catalog.GetString ("Transparancy color");
			this.hbox5.Add (this.lbTransparencyColor);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.lbTransparencyColor]));
			w24.Position = 1;
			w24.Expand = false;
			w24.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.btnColor = new global::Gtk.ColorButton ();
			this.btnColor.Sensitive = false;
			this.btnColor.CanFocus = true;
			this.btnColor.Events = ((global::Gdk.EventMask)(784));
			this.btnColor.Name = "btnColor";
			this.hbox5.Add (this.btnColor);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.btnColor]));
			w25.Position = 2;
			w25.Expand = false;
			w25.Fill = false;
			this.vbox4.Add (this.hbox5);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox5]));
			w26.Position = 3;
			w26.Expand = false;
			w26.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.rdPng32BitAlphaAsValue = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("32 Bit PNG (store alpha value)"));
			this.rdPng32BitAlphaAsValue.CanFocus = true;
			this.rdPng32BitAlphaAsValue.Name = "rdPng32BitAlphaAsValue";
			this.rdPng32BitAlphaAsValue.DrawIndicator = true;
			this.rdPng32BitAlphaAsValue.UseUnderline = true;
			this.rdPng32BitAlphaAsValue.Group = this.rdJpeg.Group;
			this.vbox4.Add (this.rdPng32BitAlphaAsValue);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.rdPng32BitAlphaAsValue]));
			w27.Position = 4;
			w27.Expand = false;
			w27.Fill = false;
			this.GtkAlignment5.Add (this.vbox4);
			this.frame4.Add (this.GtkAlignment5);
			this.GtkLabel11 = new global::Gtk.Label ();
			this.GtkLabel11.Name = "GtkLabel11";
			this.GtkLabel11.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>PNG</b>");
			this.GtkLabel11.UseMarkup = true;
			this.frame4.LabelWidget = this.GtkLabel11;
			this.VBoxImageFormat.Add (this.frame4);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.VBoxImageFormat [this.frame4]));
			w30.Position = 1;
			w30.Expand = false;
			w30.Fill = false;
			// Container child VBoxImageFormat.Gtk.Box+BoxChild
			this.frame5 = new global::Gtk.Frame ();
			this.frame5.Name = "frame5";
			this.frame5.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame5.Gtk.Container+ContainerChild
			this.GtkAlignment6 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment6.Name = "GtkAlignment6";
			this.GtkAlignment6.LeftPadding = ((uint)(12));
			// Container child GtkAlignment6.Gtk.Container+ContainerChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.rdBmp1bit = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("1 Bit BMP"));
			this.rdBmp1bit.Sensitive = false;
			this.rdBmp1bit.CanFocus = true;
			this.rdBmp1bit.Name = "rdBmp1bit";
			this.rdBmp1bit.DrawIndicator = true;
			this.rdBmp1bit.UseUnderline = true;
			this.rdBmp1bit.Group = this.rdJpeg.Group;
			this.vbox5.Add (this.rdBmp1bit);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.rdBmp1bit]));
			w31.Position = 0;
			w31.Expand = false;
			w31.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.rdBmp8bit = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("8 Bit BMP grayscale"));
			this.rdBmp8bit.CanFocus = true;
			this.rdBmp8bit.Name = "rdBmp8bit";
			this.rdBmp8bit.DrawIndicator = true;
			this.rdBmp8bit.UseUnderline = true;
			this.rdBmp8bit.Group = this.rdJpeg.Group;
			this.vbox5.Add (this.rdBmp8bit);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.rdBmp8bit]));
			w32.Position = 1;
			w32.Expand = false;
			w32.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.rdBmp24bit = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("24 Bit BMP"));
			this.rdBmp24bit.CanFocus = true;
			this.rdBmp24bit.Name = "rdBmp24bit";
			this.rdBmp24bit.DrawIndicator = true;
			this.rdBmp24bit.UseUnderline = true;
			this.rdBmp24bit.Group = this.rdJpeg.Group;
			this.vbox5.Add (this.rdBmp24bit);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.rdBmp24bit]));
			w33.Position = 2;
			w33.Expand = false;
			w33.Fill = false;
			this.GtkAlignment6.Add (this.vbox5);
			this.frame5.Add (this.GtkAlignment6);
			this.GtkLabel15 = new global::Gtk.Label ();
			this.GtkLabel15.Name = "GtkLabel15";
			this.GtkLabel15.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>BMP</b>");
			this.GtkLabel15.UseMarkup = true;
			this.frame5.LabelWidget = this.GtkLabel15;
			this.VBoxImageFormat.Add (this.frame5);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.VBoxImageFormat [this.frame5]));
			w36.Position = 2;
			w36.Expand = false;
			w36.Fill = false;
			// Container child VBoxImageFormat.Gtk.Box+BoxChild
			this.frame6 = new global::Gtk.Frame ();
			this.frame6.Name = "frame6";
			this.frame6.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame6.Gtk.Container+ContainerChild
			this.GtkAlignment7 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment7.Name = "GtkAlignment7";
			this.GtkAlignment7.LeftPadding = ((uint)(12));
			// Container child GtkAlignment7.Gtk.Container+ContainerChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.rdTiff = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("TIFF"));
			this.rdTiff.CanFocus = true;
			this.rdTiff.Name = "rdTiff";
			this.rdTiff.DrawIndicator = true;
			this.rdTiff.UseUnderline = true;
			this.rdTiff.Group = this.rdJpeg.Group;
			this.vbox7.Add (this.rdTiff);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.rdTiff]));
			w37.Position = 0;
			w37.Expand = false;
			w37.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.rdGif = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("GIF"));
			this.rdGif.CanFocus = true;
			this.rdGif.Name = "rdGif";
			this.rdGif.DrawIndicator = true;
			this.rdGif.UseUnderline = true;
			this.rdGif.Group = this.rdJpeg.Group;
			this.vbox7.Add (this.rdGif);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.rdGif]));
			w38.Position = 1;
			w38.Expand = false;
			w38.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.rdWmf = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("WMF"));
			this.rdWmf.CanFocus = true;
			this.rdWmf.Name = "rdWmf";
			this.rdWmf.DrawIndicator = true;
			this.rdWmf.UseUnderline = true;
			this.rdWmf.Group = this.rdJpeg.Group;
			this.vbox7.Add (this.rdWmf);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.rdWmf]));
			w39.Position = 2;
			w39.Expand = false;
			w39.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.rdEmf = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("EMF"));
			this.rdEmf.CanFocus = true;
			this.rdEmf.Name = "rdEmf";
			this.rdEmf.DrawIndicator = true;
			this.rdEmf.UseUnderline = true;
			this.rdEmf.Group = this.rdJpeg.Group;
			this.vbox7.Add (this.rdEmf);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.rdEmf]));
			w40.Position = 3;
			w40.Expand = false;
			w40.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.rdIcon = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("ICON"));
			this.rdIcon.CanFocus = true;
			this.rdIcon.Name = "rdIcon";
			this.rdIcon.DrawIndicator = true;
			this.rdIcon.UseUnderline = true;
			this.rdIcon.Group = this.rdJpeg.Group;
			this.vbox7.Add (this.rdIcon);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.rdIcon]));
			w41.Position = 4;
			w41.Expand = false;
			w41.Fill = false;
			this.GtkAlignment7.Add (this.vbox7);
			this.frame6.Add (this.GtkAlignment7);
			this.GtkLabel21 = new global::Gtk.Label ();
			this.GtkLabel21.Name = "GtkLabel21";
			this.GtkLabel21.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Other</b>");
			this.GtkLabel21.UseMarkup = true;
			this.frame6.LabelWidget = this.GtkLabel21;
			this.VBoxImageFormat.Add (this.frame6);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.VBoxImageFormat [this.frame6]));
			w44.Position = 3;
			w44.Expand = false;
			w44.Fill = false;
			this.GtkAlignment.Add (this.VBoxImageFormat);
			this.frameImageFormat.Add (this.GtkAlignment);
			this.lbFrameImageFormat = new global::Gtk.Label ();
			this.lbFrameImageFormat.Name = "lbFrameImageFormat";
			this.lbFrameImageFormat.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Image Format</b>");
			this.lbFrameImageFormat.UseMarkup = true;
			this.frameImageFormat.LabelWidget = this.lbFrameImageFormat;
			this.vbox2.Add (this.frameImageFormat);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frameImageFormat]));
			w47.Position = 0;
			w47.Expand = false;
			w47.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.frameImageResize = new global::Gtk.Frame ();
			this.frameImageResize.Name = "frameImageResize";
			this.frameImageResize.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frameImageResize.Gtk.Container+ContainerChild
			this.GtkAlignment8 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment8.Name = "GtkAlignment8";
			this.GtkAlignment8.LeftPadding = ((uint)(12));
			// Container child GtkAlignment8.Gtk.Container+ContainerChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.frame7 = new global::Gtk.Frame ();
			this.frame7.Name = "frame7";
			this.frame7.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame7.Gtk.Container+ContainerChild
			this.GtkAlignment9 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment9.Name = "GtkAlignment9";
			this.GtkAlignment9.LeftPadding = ((uint)(12));
			// Container child GtkAlignment9.Gtk.Container+ContainerChild
			this.rdOriginalSize = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Retain original size"));
			this.rdOriginalSize.CanFocus = true;
			this.rdOriginalSize.Name = "rdOriginalSize";
			this.rdOriginalSize.Active = true;
			this.rdOriginalSize.DrawIndicator = true;
			this.rdOriginalSize.UseUnderline = true;
			this.rdOriginalSize.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.GtkAlignment9.Add (this.rdOriginalSize);
			this.frame7.Add (this.GtkAlignment9);
			this.GtkLabel24 = new global::Gtk.Label ();
			this.GtkLabel24.Name = "GtkLabel24";
			this.GtkLabel24.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Original Size</b>");
			this.GtkLabel24.UseMarkup = true;
			this.frame7.LabelWidget = this.GtkLabel24;
			this.vbox6.Add (this.frame7);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.frame7]));
			w50.Position = 0;
			w50.Expand = false;
			w50.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.frame8 = new global::Gtk.Frame ();
			this.frame8.Name = "frame8";
			this.frame8.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame8.Gtk.Container+ContainerChild
			this.GtkAlignment10 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment10.Name = "GtkAlignment10";
			this.GtkAlignment10.LeftPadding = ((uint)(12));
			// Container child GtkAlignment10.Gtk.Container+ContainerChild
			this.vbox9 = new global::Gtk.VBox ();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.rdBiggerLength = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Use length of bigger side"));
			this.rdBiggerLength.CanFocus = true;
			this.rdBiggerLength.Name = "rdBiggerLength";
			this.rdBiggerLength.DrawIndicator = true;
			this.rdBiggerLength.UseUnderline = true;
			this.rdBiggerLength.Group = this.rdOriginalSize.Group;
			this.vbox9.Add (this.rdBiggerLength);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.rdBiggerLength]));
			w51.Position = 0;
			w51.Expand = false;
			w51.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.fixed4 = new global::Gtk.Fixed ();
			this.fixed4.WidthRequest = 10;
			this.fixed4.Name = "fixed4";
			this.fixed4.HasWindow = false;
			this.hbox7.Add (this.fixed4);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.fixed4]));
			w52.Position = 0;
			w52.Expand = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.entryBiggerLength = new global::Gtk.Entry ();
			this.entryBiggerLength.Sensitive = false;
			this.entryBiggerLength.CanFocus = true;
			this.entryBiggerLength.Name = "entryBiggerLength";
			this.entryBiggerLength.IsEditable = true;
			this.entryBiggerLength.WidthChars = 8;
			this.entryBiggerLength.MaxLength = 8;
			this.entryBiggerLength.InvisibleChar = '●';
			this.hbox7.Add (this.entryBiggerLength);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.entryBiggerLength]));
			w53.Position = 1;
			w53.Expand = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.lbPixel_BiggerLength = new global::Gtk.Label ();
			this.lbPixel_BiggerLength.Sensitive = false;
			this.lbPixel_BiggerLength.Name = "lbPixel_BiggerLength";
			this.lbPixel_BiggerLength.LabelProp = global::Mono.Unix.Catalog.GetString ("Pixel");
			this.hbox7.Add (this.lbPixel_BiggerLength);
			global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.lbPixel_BiggerLength]));
			w54.Position = 2;
			w54.Expand = false;
			w54.Fill = false;
			this.vbox9.Add (this.hbox7);
			global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.hbox7]));
			w55.Position = 1;
			w55.Expand = false;
			w55.Fill = false;
			this.GtkAlignment10.Add (this.vbox9);
			this.frame8.Add (this.GtkAlignment10);
			this.GtkLabel26 = new global::Gtk.Label ();
			this.GtkLabel26.Name = "GtkLabel26";
			this.GtkLabel26.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Length Bigger Side</b>");
			this.GtkLabel26.UseMarkup = true;
			this.frame8.LabelWidget = this.GtkLabel26;
			this.vbox6.Add (this.frame8);
			global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.frame8]));
			w58.Position = 1;
			w58.Expand = false;
			w58.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.frame9 = new global::Gtk.Frame ();
			this.frame9.Name = "frame9";
			this.frame9.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame9.Gtk.Container+ContainerChild
			this.GtkAlignment11 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment11.Name = "GtkAlignment11";
			this.GtkAlignment11.LeftPadding = ((uint)(12));
			// Container child GtkAlignment11.Gtk.Container+ContainerChild
			this.vbox8 = new global::Gtk.VBox ();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.rdFixSize = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Fix image size   (width x height)"));
			this.rdFixSize.CanFocus = true;
			this.rdFixSize.Name = "rdFixSize";
			this.rdFixSize.DrawIndicator = true;
			this.rdFixSize.UseUnderline = true;
			this.rdFixSize.Group = this.rdOriginalSize.Group;
			this.vbox8.Add (this.rdFixSize);
			global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.rdFixSize]));
			w59.Position = 0;
			w59.Expand = false;
			w59.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.WidthRequest = 10;
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.hbox3.Add (this.fixed1);
			global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.fixed1]));
			w60.Position = 0;
			w60.Expand = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.checkBtnStretch = new global::Gtk.CheckButton ();
			this.checkBtnStretch.Sensitive = false;
			this.checkBtnStretch.CanFocus = true;
			this.checkBtnStretch.Name = "checkBtnStretch";
			this.checkBtnStretch.Label = global::Mono.Unix.Catalog.GetString ("Stretch image");
			this.checkBtnStretch.DrawIndicator = true;
			this.checkBtnStretch.UseUnderline = true;
			this.hbox3.Add (this.checkBtnStretch);
			global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.checkBtnStretch]));
			w61.Position = 1;
			this.vbox8.Add (this.hbox3);
			global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox3]));
			w62.Position = 1;
			w62.Expand = false;
			w62.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.fixed3 = new global::Gtk.Fixed ();
			this.fixed3.WidthRequest = 10;
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			this.hbox6.Add (this.fixed3);
			global::Gtk.Box.BoxChild w63 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.fixed3]));
			w63.Position = 0;
			w63.Expand = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.entryFixSizeWidth = new global::Gtk.Entry ();
			this.entryFixSizeWidth.Sensitive = false;
			this.entryFixSizeWidth.CanFocus = true;
			this.entryFixSizeWidth.Name = "entryFixSizeWidth";
			this.entryFixSizeWidth.IsEditable = true;
			this.entryFixSizeWidth.WidthChars = 8;
			this.entryFixSizeWidth.MaxLength = 8;
			this.entryFixSizeWidth.InvisibleChar = '●';
			this.hbox6.Add (this.entryFixSizeWidth);
			global::Gtk.Box.BoxChild w64 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.entryFixSizeWidth]));
			w64.Position = 1;
			w64.Expand = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.lbX = new global::Gtk.Label ();
			this.lbX.Sensitive = false;
			this.lbX.Name = "lbX";
			this.lbX.LabelProp = global::Mono.Unix.Catalog.GetString ("x");
			this.hbox6.Add (this.lbX);
			global::Gtk.Box.BoxChild w65 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.lbX]));
			w65.Position = 2;
			w65.Expand = false;
			w65.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.entryFixSizeHeight = new global::Gtk.Entry ();
			this.entryFixSizeHeight.Sensitive = false;
			this.entryFixSizeHeight.CanFocus = true;
			this.entryFixSizeHeight.Name = "entryFixSizeHeight";
			this.entryFixSizeHeight.IsEditable = true;
			this.entryFixSizeHeight.WidthChars = 8;
			this.entryFixSizeHeight.MaxLength = 8;
			this.entryFixSizeHeight.InvisibleChar = '●';
			this.hbox6.Add (this.entryFixSizeHeight);
			global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.entryFixSizeHeight]));
			w66.Position = 3;
			w66.Expand = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.lbPixel_FixSize = new global::Gtk.Label ();
			this.lbPixel_FixSize.Sensitive = false;
			this.lbPixel_FixSize.Name = "lbPixel_FixSize";
			this.lbPixel_FixSize.LabelProp = global::Mono.Unix.Catalog.GetString ("Pixel");
			this.hbox6.Add (this.lbPixel_FixSize);
			global::Gtk.Box.BoxChild w67 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.lbPixel_FixSize]));
			w67.Position = 4;
			w67.Expand = false;
			w67.Fill = false;
			this.vbox8.Add (this.hbox6);
			global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox6]));
			w68.Position = 2;
			w68.Expand = false;
			w68.Fill = false;
			this.GtkAlignment11.Add (this.vbox8);
			this.frame9.Add (this.GtkAlignment11);
			this.GtkLabel30 = new global::Gtk.Label ();
			this.GtkLabel30.Name = "GtkLabel30";
			this.GtkLabel30.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Fix Image Size</b>");
			this.GtkLabel30.UseMarkup = true;
			this.frame9.LabelWidget = this.GtkLabel30;
			this.vbox6.Add (this.frame9);
			global::Gtk.Box.BoxChild w71 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.frame9]));
			w71.Position = 2;
			w71.Expand = false;
			w71.Fill = false;
			this.GtkAlignment8.Add (this.vbox6);
			this.frameImageResize.Add (this.GtkAlignment8);
			this.lbFrameImageResize = new global::Gtk.Label ();
			this.lbFrameImageResize.Name = "lbFrameImageResize";
			this.lbFrameImageResize.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Image Resize</b>");
			this.lbFrameImageResize.UseMarkup = true;
			this.frameImageResize.LabelWidget = this.lbFrameImageResize;
			this.vbox2.Add (this.frameImageResize);
			global::Gtk.Box.BoxChild w74 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frameImageResize]));
			w74.Position = 1;
			w74.Expand = false;
			w74.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.frameOutputDirectory = new global::Gtk.Frame ();
			this.frameOutputDirectory.Name = "frameOutputDirectory";
			this.frameOutputDirectory.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frameOutputDirectory.Gtk.Container+ContainerChild
			this.GtkAlignment12 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment12.Name = "GtkAlignment12";
			this.GtkAlignment12.LeftPadding = ((uint)(12));
			// Container child GtkAlignment12.Gtk.Container+ContainerChild
			this.vboxOutputDirectory = new global::Gtk.VBox ();
			this.vboxOutputDirectory.Name = "vboxOutputDirectory";
			this.vboxOutputDirectory.Spacing = 6;
			// Container child vboxOutputDirectory.Gtk.Box+BoxChild
			this.htlbOutputDirectory = new global::Picturez.HyperTextLabel ();
			this.htlbOutputDirectory.HeightRequest = 10;
			this.htlbOutputDirectory.Sensitive = false;
			this.htlbOutputDirectory.Name = "htlbOutputDirectory";
			this.htlbOutputDirectory.Sensitive = false;
			this.htlbOutputDirectory.Font = "";
			this.htlbOutputDirectory.Text = "";
			this.htlbOutputDirectory.TextSize = 0;
			this.htlbOutputDirectory.ShownTextLength = 0;
			this.htlbOutputDirectory.Underline = false;
			this.htlbOutputDirectory.Bold = false;
			this.htlbOutputDirectory.Italic = false;
			this.vboxOutputDirectory.Add (this.htlbOutputDirectory);
			global::Gtk.Box.BoxChild w75 = ((global::Gtk.Box.BoxChild)(this.vboxOutputDirectory [this.htlbOutputDirectory]));
			w75.Position = 0;
			w75.Expand = false;
			w75.Fill = false;
			// Container child vboxOutputDirectory.Gtk.Box+BoxChild
			this.checkBtnUseOriginalDirectory = new global::Gtk.CheckButton ();
			this.checkBtnUseOriginalDirectory.CanFocus = true;
			this.checkBtnUseOriginalDirectory.Name = "checkBtnUseOriginalDirectory";
			this.checkBtnUseOriginalDirectory.Label = global::Mono.Unix.Catalog.GetString ("Use original directory");
			this.checkBtnUseOriginalDirectory.DrawIndicator = true;
			this.checkBtnUseOriginalDirectory.UseUnderline = true;
			this.vboxOutputDirectory.Add (this.checkBtnUseOriginalDirectory);
			global::Gtk.Box.BoxChild w76 = ((global::Gtk.Box.BoxChild)(this.vboxOutputDirectory [this.checkBtnUseOriginalDirectory]));
			w76.Position = 1;
			w76.Expand = false;
			w76.Fill = false;
			// Container child vboxOutputDirectory.Gtk.Box+BoxChild
			this.checkBtnOverwriteOriginalImage = new global::Gtk.CheckButton ();
			this.checkBtnOverwriteOriginalImage.CanFocus = true;
			this.checkBtnOverwriteOriginalImage.Name = "checkBtnOverwriteOriginalImage";
			this.checkBtnOverwriteOriginalImage.Label = global::Mono.Unix.Catalog.GetString ("Overwrite/Delete original image");
			this.checkBtnOverwriteOriginalImage.DrawIndicator = true;
			this.checkBtnOverwriteOriginalImage.UseUnderline = true;
			this.vboxOutputDirectory.Add (this.checkBtnOverwriteOriginalImage);
			global::Gtk.Box.BoxChild w77 = ((global::Gtk.Box.BoxChild)(this.vboxOutputDirectory [this.checkBtnOverwriteOriginalImage]));
			w77.Position = 2;
			w77.Expand = false;
			w77.Fill = false;
			this.GtkAlignment12.Add (this.vboxOutputDirectory);
			this.frameOutputDirectory.Add (this.GtkAlignment12);
			this.lbFrameOutputDirectory = new global::Gtk.Label ();
			this.lbFrameOutputDirectory.Name = "lbFrameOutputDirectory";
			this.lbFrameOutputDirectory.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Output Directory</b>");
			this.lbFrameOutputDirectory.UseMarkup = true;
			this.frameOutputDirectory.LabelWidget = this.lbFrameOutputDirectory;
			this.vbox2.Add (this.frameOutputDirectory);
			global::Gtk.Box.BoxChild w80 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frameOutputDirectory]));
			w80.Position = 2;
			w80.Expand = false;
			w80.Fill = false;
			this.hbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w81 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox2]));
			w81.Position = 1;
			w81.Padding = ((uint)(3));
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w82 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w82.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.progressbar1 = new global::Gtk.ProgressBar ();
			this.progressbar1.Name = "progressbar1";
			this.progressbar1.Text = global::Mono.Unix.Catalog.GetString (" ");
			this.vbox1.Add (this.progressbar1);
			global::Gtk.Box.BoxChild w83 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.progressbar1]));
			w83.Position = 2;
			w83.Expand = false;
			w83.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.btnConvert = new global::Picturez.PicturezButton ();
			this.btnConvert.Name = "btnConvert";
			this.btnConvert.CheckReleaseState = false;
			this.btnConvert.BorderlineWidth = 3;
			this.btnConvert.ButtonHeight = 40;
			this.btnConvert.Font = "Arial";
			this.btnConvert.Text = "Convert";
			this.btnConvert.TextSize = 18;
			this.vbox1.Add (this.btnConvert);
			global::Gtk.Box.BoxChild w84 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.btnConvert]));
			w84.Position = 3;
			w84.Padding = ((uint)(3));
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			w1.SetUiManager (UIManager);
			this.Hide ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.DragDrop += new global::Gtk.DragDropHandler (this.OnDragDrop);
			this.DragDataReceived += new global::Gtk.DragDataReceivedHandler (this.OnDragDataReceived);
			this.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.OnKeyPressEvent);
			this.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler (this.OnKeyReleaseEvent);
			this.rdJpeg.Toggled += new global::System.EventHandler (this.OnRdJpegToggled);
			this.hscaleQuality.ValueChanged += new global::System.EventHandler (this.OnHscaleQualityValueChanged);
			this.rdJpegGray.Toggled += new global::System.EventHandler (this.OnRdJpegGrayToggled);
			this.rdPng1bit.Toggled += new global::System.EventHandler (this.OnRdPng1bitToggled);
			this.rdPng8Bit.Toggled += new global::System.EventHandler (this.OnRdPng8BitToggled);
			this.rdPng24Bit.Toggled += new global::System.EventHandler (this.OnRdPng24BitToggled);
			this.rdPNG32bit.Toggled += new global::System.EventHandler (this.OnRdPNG32bitToggled);
			this.btnColor.ColorSet += new global::System.EventHandler (this.OnBtnColorColorSet);
			this.rdPng32BitAlphaAsValue.Toggled += new global::System.EventHandler (this.OnRdPng32BitAlphaAsValueToggled);
			this.rdBmp1bit.Toggled += new global::System.EventHandler (this.OnRdBmp1bitToggled);
			this.rdBmp8bit.Toggled += new global::System.EventHandler (this.OnRdBmp8bitToggled);
			this.rdBmp24bit.Toggled += new global::System.EventHandler (this.OnRdBmp24bitToggled);
			this.rdTiff.Toggled += new global::System.EventHandler (this.OnRdTiffToggled);
			this.rdGif.Toggled += new global::System.EventHandler (this.OnRdGifToggled);
			this.rdWmf.Toggled += new global::System.EventHandler (this.OnRdWmfToggled);
			this.rdEmf.Toggled += new global::System.EventHandler (this.OnRdEmfToggled);
			this.rdIcon.Toggled += new global::System.EventHandler (this.OnRdIconToggled);
			this.rdOriginalSize.Toggled += new global::System.EventHandler (this.OnRdOriginalSizeToggled);
			this.rdBiggerLength.Toggled += new global::System.EventHandler (this.OnRdBiggerLengthToggled);
			this.entryBiggerLength.TextInserted += new global::Gtk.TextInsertedHandler (this.OnEntryBiggerLengthTextInserted);
			this.rdFixSize.Toggled += new global::System.EventHandler (this.OnRdFixSizeToggled);
			this.checkBtnStretch.Toggled += new global::System.EventHandler (this.OnCheckButtonsToggled);
			this.entryFixSizeWidth.TextInserted += new global::Gtk.TextInsertedHandler (this.OnEntryFixSizeWidthTextInserted);
			this.entryFixSizeHeight.TextInserted += new global::Gtk.TextInsertedHandler (this.OnEntryFixSizeHeightTextInserted);
			this.checkBtnUseOriginalDirectory.Toggled += new global::System.EventHandler (this.OnCheckButtonsToggled);
			this.checkBtnOverwriteOriginalImage.Toggled += new global::System.EventHandler (this.OnCheckButtonsToggled);
			this.btnConvert.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnBtnConvertReleased);
		}
	}
}
