
// This file has been generated by the GUI designer. Do not modify.
namespace Picturez
{
	public partial class FilterWidget
	{
		private global::Gtk.VBox vboxA;
		private global::Gtk.HBox hbox1;
		private global::Gtk.VBox vboxImagePanel;
		private global::Picturez.SimpleImagePanel simpleimagepanel1;
		private global::Gtk.CheckButton checkBtnLivePreview;
		private global::Gtk.VBox vbox1;
		private global::Gtk.Frame frameSteganography;
		private global::Gtk.Alignment AlignmentFrameSteganography;
		private global::Gtk.VBox vboxSteganography;
		private global::Gtk.Frame frameModus;
		private global::Gtk.Alignment AlignmentFrameModus;
		private global::Gtk.HBox hboxModus;
		private global::Gtk.RadioButton rdBtnRead;
		private global::Gtk.RadioButton rdBtnWrite;
		private global::Gtk.Label lbFrameModus;
		private global::Gtk.Frame frame_combobox1;
		private global::Gtk.Alignment alignment_combobox1;
		private global::Gtk.ComboBox combobox1;
		private global::Gtk.Label lbFrame_combobox1;
		private global::Gtk.Frame frame_hscale1;
		private global::Gtk.Alignment alignment_hscale1;
		private global::Gtk.HScale hscale1;
		private global::Gtk.Label lbFrame_hscale1;
		private global::Gtk.Label lbFrameSteganography;
		private global::Gtk.Frame frameCursorPos;
		private global::Gtk.Alignment GtkAlignment1;
		private global::Gtk.Label lbCursorPos;
		private global::Gtk.Label lbFrameCursorPos;
		private global::Gtk.HBox hboxButtons;
		private global::Picturez.PicturezButton btnCancel;
		private global::Picturez.PicturezButton btnOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Picturez.FilterWidget
			this.Name = "Picturez.FilterWidget";
			this.Title = global::Mono.Unix.Catalog.GetString ("FilterWidget");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Picturez.FilterWidget.Gtk.Container+ContainerChild
			this.vboxA = new global::Gtk.VBox ();
			this.vboxA.Name = "vboxA";
			this.vboxA.Spacing = 6;
			// Container child vboxA.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vboxImagePanel = new global::Gtk.VBox ();
			this.vboxImagePanel.Name = "vboxImagePanel";
			this.vboxImagePanel.Spacing = 6;
			// Container child vboxImagePanel.Gtk.Box+BoxChild
			this.simpleimagepanel1 = new global::Picturez.SimpleImagePanel ();
			this.simpleimagepanel1.Events = ((global::Gdk.EventMask)(256));
			this.simpleimagepanel1.Name = "simpleimagepanel1";
			this.simpleimagepanel1.ScaleCursorX = 0F;
			this.simpleimagepanel1.ScaleCursorY = 0F;
			this.vboxImagePanel.Add (this.simpleimagepanel1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vboxImagePanel [this.simpleimagepanel1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vboxImagePanel.Gtk.Box+BoxChild
			this.checkBtnLivePreview = new global::Gtk.CheckButton ();
			this.checkBtnLivePreview.CanFocus = true;
			this.checkBtnLivePreview.Name = "checkBtnLivePreview";
			this.checkBtnLivePreview.Label = global::Mono.Unix.Catalog.GetString ("Live Preview");
			this.checkBtnLivePreview.DrawIndicator = true;
			this.checkBtnLivePreview.UseUnderline = true;
			this.vboxImagePanel.Add (this.checkBtnLivePreview);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vboxImagePanel [this.checkBtnLivePreview]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.hbox1.Add (this.vboxImagePanel);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vboxImagePanel]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.frameSteganography = new global::Gtk.Frame ();
			this.frameSteganography.Name = "frameSteganography";
			this.frameSteganography.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frameSteganography.Gtk.Container+ContainerChild
			this.AlignmentFrameSteganography = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.AlignmentFrameSteganography.Name = "AlignmentFrameSteganography";
			this.AlignmentFrameSteganography.LeftPadding = ((uint)(12));
			this.AlignmentFrameSteganography.RightPadding = ((uint)(12));
			this.AlignmentFrameSteganography.BottomPadding = ((uint)(12));
			// Container child AlignmentFrameSteganography.Gtk.Container+ContainerChild
			this.vboxSteganography = new global::Gtk.VBox ();
			this.vboxSteganography.Name = "vboxSteganography";
			this.vboxSteganography.Spacing = 6;
			// Container child vboxSteganography.Gtk.Box+BoxChild
			this.frameModus = new global::Gtk.Frame ();
			this.frameModus.Name = "frameModus";
			this.frameModus.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frameModus.Gtk.Container+ContainerChild
			this.AlignmentFrameModus = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.AlignmentFrameModus.Name = "AlignmentFrameModus";
			this.AlignmentFrameModus.LeftPadding = ((uint)(12));
			// Container child AlignmentFrameModus.Gtk.Container+ContainerChild
			this.hboxModus = new global::Gtk.HBox ();
			this.hboxModus.Name = "hboxModus";
			this.hboxModus.Spacing = 6;
			// Container child hboxModus.Gtk.Box+BoxChild
			this.rdBtnRead = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Read"));
			this.rdBtnRead.CanFocus = true;
			this.rdBtnRead.Name = "rdBtnRead";
			this.rdBtnRead.DrawIndicator = true;
			this.rdBtnRead.UseUnderline = true;
			this.rdBtnRead.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.hboxModus.Add (this.rdBtnRead);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hboxModus [this.rdBtnRead]));
			w4.Position = 0;
			// Container child hboxModus.Gtk.Box+BoxChild
			this.rdBtnWrite = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Write"));
			this.rdBtnWrite.CanFocus = true;
			this.rdBtnWrite.Name = "rdBtnWrite";
			this.rdBtnWrite.DrawIndicator = true;
			this.rdBtnWrite.UseUnderline = true;
			this.rdBtnWrite.Group = this.rdBtnRead.Group;
			this.hboxModus.Add (this.rdBtnWrite);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hboxModus [this.rdBtnWrite]));
			w5.Position = 1;
			this.AlignmentFrameModus.Add (this.hboxModus);
			this.frameModus.Add (this.AlignmentFrameModus);
			this.lbFrameModus = new global::Gtk.Label ();
			this.lbFrameModus.Name = "lbFrameModus";
			this.lbFrameModus.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Modus</b>");
			this.lbFrameModus.UseMarkup = true;
			this.frameModus.LabelWidget = this.lbFrameModus;
			this.vboxSteganography.Add (this.frameModus);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vboxSteganography [this.frameModus]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vboxSteganography.Gtk.Box+BoxChild
			this.frame_combobox1 = new global::Gtk.Frame ();
			this.frame_combobox1.Name = "frame_combobox1";
			this.frame_combobox1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frame_combobox1.Gtk.Container+ContainerChild
			this.alignment_combobox1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.alignment_combobox1.Name = "alignment_combobox1";
			this.alignment_combobox1.LeftPadding = ((uint)(12));
			// Container child alignment_combobox1.Gtk.Container+ContainerChild
			this.combobox1 = global::Gtk.ComboBox.NewText ();
			this.combobox1.Name = "combobox1";
			this.alignment_combobox1.Add (this.combobox1);
			this.frame_combobox1.Add (this.alignment_combobox1);
			this.lbFrame_combobox1 = new global::Gtk.Label ();
			this.lbFrame_combobox1.Name = "lbFrame_combobox1";
			this.lbFrame_combobox1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>combobox1</b>");
			this.lbFrame_combobox1.UseMarkup = true;
			this.frame_combobox1.LabelWidget = this.lbFrame_combobox1;
			this.vboxSteganography.Add (this.frame_combobox1);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vboxSteganography [this.frame_combobox1]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vboxSteganography.Gtk.Box+BoxChild
			this.frame_hscale1 = new global::Gtk.Frame ();
			this.frame_hscale1.Name = "frame_hscale1";
			this.frame_hscale1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frame_hscale1.Gtk.Container+ContainerChild
			this.alignment_hscale1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.alignment_hscale1.Name = "alignment_hscale1";
			this.alignment_hscale1.LeftPadding = ((uint)(12));
			// Container child alignment_hscale1.Gtk.Container+ContainerChild
			this.hscale1 = new global::Gtk.HScale (null);
			this.hscale1.CanFocus = true;
			this.hscale1.Name = "hscale1";
			this.hscale1.Adjustment.Upper = 100;
			this.hscale1.Adjustment.PageIncrement = 10;
			this.hscale1.Adjustment.StepIncrement = 1;
			this.hscale1.DrawValue = true;
			this.hscale1.Digits = 0;
			this.hscale1.ValuePos = ((global::Gtk.PositionType)(2));
			this.alignment_hscale1.Add (this.hscale1);
			this.frame_hscale1.Add (this.alignment_hscale1);
			this.lbFrame_hscale1 = new global::Gtk.Label ();
			this.lbFrame_hscale1.Name = "lbFrame_hscale1";
			this.lbFrame_hscale1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>hscale1</b>");
			this.lbFrame_hscale1.UseMarkup = true;
			this.frame_hscale1.LabelWidget = this.lbFrame_hscale1;
			this.vboxSteganography.Add (this.frame_hscale1);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vboxSteganography [this.frame_hscale1]));
			w14.Position = 2;
			w14.Expand = false;
			w14.Fill = false;
			this.AlignmentFrameSteganography.Add (this.vboxSteganography);
			this.frameSteganography.Add (this.AlignmentFrameSteganography);
			this.lbFrameSteganography = new global::Gtk.Label ();
			this.lbFrameSteganography.Name = "lbFrameSteganography";
			this.lbFrameSteganography.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Steganography</b>");
			this.lbFrameSteganography.UseMarkup = true;
			this.frameSteganography.LabelWidget = this.lbFrameSteganography;
			this.vbox1.Add (this.frameSteganography);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frameSteganography]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.frameCursorPos = new global::Gtk.Frame ();
			this.frameCursorPos.Name = "frameCursorPos";
			this.frameCursorPos.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frameCursorPos.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.lbCursorPos = new global::Gtk.Label ();
			this.lbCursorPos.Name = "lbCursorPos";
			this.lbCursorPos.LabelProp = global::Mono.Unix.Catalog.GetString ("0 x 0");
			this.GtkAlignment1.Add (this.lbCursorPos);
			this.frameCursorPos.Add (this.GtkAlignment1);
			this.lbFrameCursorPos = new global::Gtk.Label ();
			this.lbFrameCursorPos.Name = "lbFrameCursorPos";
			this.lbFrameCursorPos.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Cursor position</b>");
			this.lbFrameCursorPos.UseMarkup = true;
			this.frameCursorPos.LabelWidget = this.lbFrameCursorPos;
			this.vbox1.Add (this.frameCursorPos);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frameCursorPos]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hboxButtons = new global::Gtk.HBox ();
			this.hboxButtons.Name = "hboxButtons";
			this.hboxButtons.Spacing = 6;
			// Container child hboxButtons.Gtk.Box+BoxChild
			this.btnCancel = new global::Picturez.PicturezButton ();
			this.btnCancel.Name = "btnCancel";
			this.btnCancel.CheckReleaseState = false;
			this.btnCancel.BorderlineWidth = 3;
			this.btnCancel.ButtonHeight = 35;
			this.btnCancel.Font = "Arial";
			this.btnCancel.Text = "Cancel";
			this.btnCancel.TextSize = 14;
			this.hboxButtons.Add (this.btnCancel);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hboxButtons [this.btnCancel]));
			w21.Position = 0;
			// Container child hboxButtons.Gtk.Box+BoxChild
			this.btnOk = new global::Picturez.PicturezButton ();
			this.btnOk.Name = "btnOk";
			this.btnOk.CheckReleaseState = false;
			this.btnOk.BorderlineWidth = 3;
			this.btnOk.ButtonHeight = 35;
			this.btnOk.Font = "Arial";
			this.btnOk.Text = "OK";
			this.btnOk.TextSize = 14;
			this.hboxButtons.Add (this.btnOk);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hboxButtons [this.btnOk]));
			w22.Position = 1;
			this.vbox1.Add (this.hboxButtons);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hboxButtons]));
			w23.Position = 2;
			w23.Expand = false;
			w23.Fill = false;
			this.hbox1.Add (this.vbox1);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox1]));
			w24.Position = 1;
			w24.Padding = ((uint)(5));
			this.vboxA.Add (this.hbox1);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vboxA [this.hbox1]));
			w25.Position = 0;
			this.Add (this.vboxA);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 524;
			this.DefaultHeight = 361;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.btnOk.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnBtnOkButtonReleaseEvent);
		}
	}
}
