
// This file has been generated by the GUI designer. Do not modify.
namespace Troonie
{
	public partial class FilterWidget
	{
		private global::Gtk.VBox vboxA;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.VBox vboxImagePanel;
		
		private global::Troonie.SimpleImagePanel simpleimagepanel1;
		
		private global::Gtk.CheckButton checkBtnUse255ForAlpha;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.Frame frameComboboxes;
		
		private global::Gtk.Alignment AlignmentFrameComboboxes;
		
		private global::Gtk.VBox vboxSteganography1;
		
		private global::Gtk.Frame frame_combobox1;
		
		private global::Gtk.Alignment alignment_combobox1;
		
		private global::Gtk.ComboBox combobox1;
		
		private global::Gtk.Label lbFrame_combobox1;
		
		private global::Gtk.Frame frame_combobox2;
		
		private global::Gtk.Alignment alignment_combobox2;
		
		private global::Gtk.ComboBox combobox2;
		
		private global::Gtk.Label lbFrame_combobox2;
		
		private global::Gtk.Frame frame_combobox3;
		
		private global::Gtk.Alignment alignment_combobox3;
		
		private global::Gtk.ComboBox combobox3;
		
		private global::Gtk.Label lbFrame_combobox3;
		
		private global::Gtk.Frame frameHScales;
		
		private global::Gtk.Alignment AlignmentFrameHScales;
		
		private global::Gtk.VBox vboxFrameHScales;
		
		private global::Gtk.Frame frame_hscale1;
		
		private global::Gtk.Alignment alignment_hscale1;
		
		private global::Gtk.HScale hscale1;
		
		private global::Gtk.Label lbFrame_hscale1;
		
		private global::Gtk.Frame frame_hscale2;
		
		private global::Gtk.Alignment alignment_hscale2;
		
		private global::Gtk.HScale hscale2;
		
		private global::Gtk.Label lbFrame_hscale2;
		
		private global::Gtk.Frame frame_hscale3;
		
		private global::Gtk.Alignment alignment_hscale3;
		
		private global::Gtk.HScale hscale3;
		
		private global::Gtk.Label lbFrame_hscale3;
		
		private global::Gtk.Frame frame_hscale4;
		
		private global::Gtk.Alignment alignment_hscale4;
		
		private global::Gtk.HScale hscale4;
		
		private global::Gtk.Label lbFrame_hscale4;
		
		private global::Gtk.Frame frame_hscale5;
		
		private global::Gtk.Alignment alignment_hscale5;
		
		private global::Gtk.HScale hscale5;
		
		private global::Gtk.Label lbFrame_hscale5;
		
		private global::Gtk.Frame frameCursorPos;
		
		private global::Gtk.Alignment GtkAlignment1;
		
		private global::Gtk.Label lbCursorPos;
		
		private global::Gtk.Label lbFrameCursorPos;
		
		private global::Gtk.HBox hboxButtons;
		
		private global::Troonie.TroonieButton btnCancel;
		
		private global::Troonie.TroonieButton btnOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Troonie.FilterWidget
			this.Name = "Troonie.FilterWidget";
			this.Title = ("FilterWidget");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Troonie.FilterWidget.Gtk.Container+ContainerChild
			this.vboxA = new global::Gtk.VBox ();
			this.vboxA.Name = "vboxA";
			this.vboxA.Spacing = 6;
			// Container child vboxA.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vboxImagePanel = new global::Gtk.VBox ();
			this.vboxImagePanel.Name = "vboxImagePanel";
			this.vboxImagePanel.Spacing = 6;
			// Container child vboxImagePanel.Gtk.Box+BoxChild
			this.simpleimagepanel1 = new global::Troonie.SimpleImagePanel ();
			this.simpleimagepanel1.Events = ((global::Gdk.EventMask)(256));
			this.simpleimagepanel1.Name = "simpleimagepanel1";
			this.simpleimagepanel1.ScaleCursorX = 0F;
			this.simpleimagepanel1.ScaleCursorY = 0F;
			this.vboxImagePanel.Add (this.simpleimagepanel1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vboxImagePanel [this.simpleimagepanel1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			w1.Padding = ((uint)(5));
			// Container child vboxImagePanel.Gtk.Box+BoxChild
			this.checkBtnUse255ForAlpha = new global::Gtk.CheckButton ();
			this.checkBtnUse255ForAlpha.CanFocus = true;
			this.checkBtnUse255ForAlpha.Name = "checkBtnUse255ForAlpha";
			this.checkBtnUse255ForAlpha.Label = ("255 for Alpha channel");
			this.checkBtnUse255ForAlpha.DrawIndicator = true;
			this.checkBtnUse255ForAlpha.UseUnderline = true;
			this.vboxImagePanel.Add (this.checkBtnUse255ForAlpha);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vboxImagePanel [this.checkBtnUse255ForAlpha]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.hbox1.Add (this.vboxImagePanel);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vboxImagePanel]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			w3.Padding = ((uint)(5));
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.frameComboboxes = new global::Gtk.Frame ();
			this.frameComboboxes.Name = "frameComboboxes";
			// Container child frameComboboxes.Gtk.Container+ContainerChild
			this.AlignmentFrameComboboxes = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.AlignmentFrameComboboxes.Name = "AlignmentFrameComboboxes";
			this.AlignmentFrameComboboxes.LeftPadding = ((uint)(12));
			this.AlignmentFrameComboboxes.RightPadding = ((uint)(12));
			this.AlignmentFrameComboboxes.BottomPadding = ((uint)(12));
			// Container child AlignmentFrameComboboxes.Gtk.Container+ContainerChild
			this.vboxSteganography1 = new global::Gtk.VBox ();
			this.vboxSteganography1.Name = "vboxSteganography1";
			this.vboxSteganography1.Spacing = 6;
			// Container child vboxSteganography1.Gtk.Box+BoxChild
			this.frame_combobox1 = new global::Gtk.Frame ();
			this.frame_combobox1.Name = "frame_combobox1";
			// Container child frame_combobox1.Gtk.Container+ContainerChild
			this.alignment_combobox1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.alignment_combobox1.Name = "alignment_combobox1";
			this.alignment_combobox1.LeftPadding = ((uint)(12));
			// Container child alignment_combobox1.Gtk.Container+ContainerChild
			this.combobox1 = new global::Gtk.ComboBox();
			this.combobox1.Name = "combobox1";
			this.alignment_combobox1.Add (this.combobox1);
			this.frame_combobox1.Add (this.alignment_combobox1);
			this.lbFrame_combobox1 = new global::Gtk.Label ();
			this.lbFrame_combobox1.Name = "lbFrame_combobox1";
			this.lbFrame_combobox1.LabelProp = ("<b>combobox1</b>");
			this.lbFrame_combobox1.UseMarkup = true;
			this.frame_combobox1.LabelWidget = this.lbFrame_combobox1;
			this.vboxSteganography1.Add (this.frame_combobox1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vboxSteganography1 [this.frame_combobox1]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vboxSteganography1.Gtk.Box+BoxChild
			this.frame_combobox2 = new global::Gtk.Frame ();
			this.frame_combobox2.Name = "frame_combobox2";
			// Container child frame_combobox2.Gtk.Container+ContainerChild
			this.alignment_combobox2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.alignment_combobox2.Name = "alignment_combobox2";
			this.alignment_combobox2.LeftPadding = ((uint)(12));
			// Container child alignment_combobox2.Gtk.Container+ContainerChild
			this.combobox2 = new Gtk.ComboBox(); // global::Gtk.ComboBox.NewText ();
			this.combobox2.Name = "combobox2";
			this.alignment_combobox2.Add (this.combobox2);
			this.frame_combobox2.Add (this.alignment_combobox2);
			this.lbFrame_combobox2 = new global::Gtk.Label ();
			this.lbFrame_combobox2.Name = "lbFrame_combobox2";
			this.lbFrame_combobox2.LabelProp = ("<b>combobox2</b>");
			this.lbFrame_combobox2.UseMarkup = true;
			this.frame_combobox2.LabelWidget = this.lbFrame_combobox2;
			this.vboxSteganography1.Add (this.frame_combobox2);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vboxSteganography1 [this.frame_combobox2]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vboxSteganography1.Gtk.Box+BoxChild
			this.frame_combobox3 = new global::Gtk.Frame ();
			this.frame_combobox3.Name = "frame_combobox3";
			// Container child frame_combobox3.Gtk.Container+ContainerChild
			this.alignment_combobox3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.alignment_combobox3.Name = "alignment_combobox3";
			this.alignment_combobox3.LeftPadding = ((uint)(12));
			// Container child alignment_combobox3.Gtk.Container+ContainerChild
			this.combobox3 = new Gtk.ComboBox(); //global::Gtk.ComboBox.NewText ();
			this.combobox3.Name = "combobox3";
			this.alignment_combobox3.Add (this.combobox3);
			this.frame_combobox3.Add (this.alignment_combobox3);
			this.lbFrame_combobox3 = new global::Gtk.Label ();
			this.lbFrame_combobox3.Name = "lbFrame_combobox3";
			this.lbFrame_combobox3.LabelProp = ("<b>combobox3</b>");
			this.lbFrame_combobox3.UseMarkup = true;
			this.frame_combobox3.LabelWidget = this.lbFrame_combobox3;
			this.vboxSteganography1.Add (this.frame_combobox3);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vboxSteganography1 [this.frame_combobox3]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			this.AlignmentFrameComboboxes.Add (this.vboxSteganography1);
			this.frameComboboxes.Add (this.AlignmentFrameComboboxes);
			this.vbox1.Add (this.frameComboboxes);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frameComboboxes]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.frameHScales = new global::Gtk.Frame ();
			this.frameHScales.Name = "frameHScales";
			// Container child frameHScales.Gtk.Container+ContainerChild
			this.AlignmentFrameHScales = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.AlignmentFrameHScales.Name = "AlignmentFrameHScales";
			this.AlignmentFrameHScales.LeftPadding = ((uint)(12));
			this.AlignmentFrameHScales.RightPadding = ((uint)(12));
			this.AlignmentFrameHScales.BottomPadding = ((uint)(12));
			// Container child AlignmentFrameHScales.Gtk.Container+ContainerChild
			this.vboxFrameHScales = new global::Gtk.VBox ();
			this.vboxFrameHScales.Name = "vboxFrameHScales";
			this.vboxFrameHScales.Spacing = 6;
			// Container child vboxFrameHScales.Gtk.Box+BoxChild
			this.frame_hscale1 = new global::Gtk.Frame ();
			this.frame_hscale1.Name = "frame_hscale1";
			// Container child frame_hscale1.Gtk.Container+ContainerChild
			this.alignment_hscale1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.alignment_hscale1.Name = "alignment_hscale1";
			this.alignment_hscale1.LeftPadding = ((uint)(12));
			// Container child alignment_hscale1.Gtk.Container+ContainerChild
			this.hscale1 = new global::Gtk.HScale (null);
			this.hscale1.CanFocus = true;
			this.hscale1.Name = "hscale1";
			this.hscale1.Adjustment.Upper = 100D;
			this.hscale1.Adjustment.PageIncrement = 10D;
			this.hscale1.Adjustment.StepIncrement = 1D;
			this.hscale1.DrawValue = true;
			this.hscale1.Digits = 0;
			this.hscale1.ValuePos = ((global::Gtk.PositionType)(2));
			this.alignment_hscale1.Add (this.hscale1);
			this.frame_hscale1.Add (this.alignment_hscale1);
			this.lbFrame_hscale1 = new global::Gtk.Label ();
			this.lbFrame_hscale1.Name = "lbFrame_hscale1";
			this.lbFrame_hscale1.LabelProp = ("<b>hscale1</b>");
			this.lbFrame_hscale1.UseMarkup = true;
			this.frame_hscale1.LabelWidget = this.lbFrame_hscale1;
			this.vboxFrameHScales.Add (this.frame_hscale1);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vboxFrameHScales [this.frame_hscale1]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vboxFrameHScales.Gtk.Box+BoxChild
			this.frame_hscale2 = new global::Gtk.Frame ();
			this.frame_hscale2.Name = "frame_hscale2";
			// Container child frame_hscale2.Gtk.Container+ContainerChild
			this.alignment_hscale2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.alignment_hscale2.Name = "alignment_hscale2";
			this.alignment_hscale2.LeftPadding = ((uint)(12));
			// Container child alignment_hscale2.Gtk.Container+ContainerChild
			this.hscale2 = new global::Gtk.HScale (null);
			this.hscale2.CanFocus = true;
			this.hscale2.Name = "hscale2";
			this.hscale2.Adjustment.Upper = 100D;
			this.hscale2.Adjustment.PageIncrement = 10D;
			this.hscale2.Adjustment.StepIncrement = 1D;
			this.hscale2.DrawValue = true;
			this.hscale2.Digits = 0;
			this.hscale2.ValuePos = ((global::Gtk.PositionType)(2));
			this.alignment_hscale2.Add (this.hscale2);
			this.frame_hscale2.Add (this.alignment_hscale2);
			this.lbFrame_hscale2 = new global::Gtk.Label ();
			this.lbFrame_hscale2.Name = "lbFrame_hscale2";
			this.lbFrame_hscale2.LabelProp = ("<b>hscale2</b>");
			this.lbFrame_hscale2.UseMarkup = true;
			this.frame_hscale2.LabelWidget = this.lbFrame_hscale2;
			this.vboxFrameHScales.Add (this.frame_hscale2);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vboxFrameHScales [this.frame_hscale2]));
			w21.Position = 1;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vboxFrameHScales.Gtk.Box+BoxChild
			this.frame_hscale3 = new global::Gtk.Frame ();
			this.frame_hscale3.Name = "frame_hscale3";
			// Container child frame_hscale3.Gtk.Container+ContainerChild
			this.alignment_hscale3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.alignment_hscale3.Name = "alignment_hscale3";
			this.alignment_hscale3.LeftPadding = ((uint)(12));
			// Container child alignment_hscale3.Gtk.Container+ContainerChild
			this.hscale3 = new global::Gtk.HScale (null);
			this.hscale3.CanFocus = true;
			this.hscale3.Name = "hscale3";
			this.hscale3.Adjustment.Upper = 100D;
			this.hscale3.Adjustment.PageIncrement = 10D;
			this.hscale3.Adjustment.StepIncrement = 1D;
			this.hscale3.DrawValue = true;
			this.hscale3.Digits = 0;
			this.hscale3.ValuePos = ((global::Gtk.PositionType)(2));
			this.alignment_hscale3.Add (this.hscale3);
			this.frame_hscale3.Add (this.alignment_hscale3);
			this.lbFrame_hscale3 = new global::Gtk.Label ();
			this.lbFrame_hscale3.Name = "lbFrame_hscale3";
			this.lbFrame_hscale3.LabelProp = ("<b>hscale3</b>");
			this.lbFrame_hscale3.UseMarkup = true;
			this.frame_hscale3.LabelWidget = this.lbFrame_hscale3;
			this.vboxFrameHScales.Add (this.frame_hscale3);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vboxFrameHScales [this.frame_hscale3]));
			w24.Position = 2;
			w24.Expand = false;
			w24.Fill = false;
			// Container child vboxFrameHScales.Gtk.Box+BoxChild
			this.frame_hscale4 = new global::Gtk.Frame ();
			this.frame_hscale4.Name = "frame_hscale4";
			// Container child frame_hscale4.Gtk.Container+ContainerChild
			this.alignment_hscale4 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.alignment_hscale4.Name = "alignment_hscale4";
			this.alignment_hscale4.LeftPadding = ((uint)(12));
			// Container child alignment_hscale4.Gtk.Container+ContainerChild
			this.hscale4 = new global::Gtk.HScale (null);
			this.hscale4.CanFocus = true;
			this.hscale4.Name = "hscale4";
			this.hscale4.Adjustment.Upper = 100D;
			this.hscale4.Adjustment.PageIncrement = 10D;
			this.hscale4.Adjustment.StepIncrement = 1D;
			this.hscale4.DrawValue = true;
			this.hscale4.Digits = 0;
			this.hscale4.ValuePos = ((global::Gtk.PositionType)(2));
			this.alignment_hscale4.Add (this.hscale4);
			this.frame_hscale4.Add (this.alignment_hscale4);
			this.lbFrame_hscale4 = new global::Gtk.Label ();
			this.lbFrame_hscale4.Name = "lbFrame_hscale4";
			this.lbFrame_hscale4.LabelProp = ("<b>hscale4</b>");
			this.lbFrame_hscale4.UseMarkup = true;
			this.frame_hscale4.LabelWidget = this.lbFrame_hscale4;
			this.vboxFrameHScales.Add (this.frame_hscale4);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vboxFrameHScales [this.frame_hscale4]));
			w27.Position = 3;
			w27.Expand = false;
			w27.Fill = false;
			// Container child vboxFrameHScales.Gtk.Box+BoxChild
			this.frame_hscale5 = new global::Gtk.Frame ();
			this.frame_hscale5.Name = "frame_hscale5";
			// Container child frame_hscale5.Gtk.Container+ContainerChild
			this.alignment_hscale5 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.alignment_hscale5.Name = "alignment_hscale5";
			this.alignment_hscale5.LeftPadding = ((uint)(12));
			// Container child alignment_hscale5.Gtk.Container+ContainerChild
			this.hscale5 = new global::Gtk.HScale (null);
			this.hscale5.CanFocus = true;
			this.hscale5.Name = "hscale5";
			this.hscale5.Adjustment.Upper = 100D;
			this.hscale5.Adjustment.PageIncrement = 10D;
			this.hscale5.Adjustment.StepIncrement = 1D;
			this.hscale5.DrawValue = true;
			this.hscale5.Digits = 0;
			this.hscale5.ValuePos = ((global::Gtk.PositionType)(2));
			this.alignment_hscale5.Add (this.hscale5);
			this.frame_hscale5.Add (this.alignment_hscale5);
			this.lbFrame_hscale5 = new global::Gtk.Label ();
			this.lbFrame_hscale5.Name = "lbFrame_hscale5";
			this.lbFrame_hscale5.LabelProp = ("<b>hscale5</b>");
			this.lbFrame_hscale5.UseMarkup = true;
			this.frame_hscale5.LabelWidget = this.lbFrame_hscale5;
			this.vboxFrameHScales.Add (this.frame_hscale5);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vboxFrameHScales [this.frame_hscale5]));
			w30.Position = 4;
			w30.Expand = false;
			w30.Fill = false;
			this.AlignmentFrameHScales.Add (this.vboxFrameHScales);
			this.frameHScales.Add (this.AlignmentFrameHScales);
			this.vbox1.Add (this.frameHScales);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frameHScales]));
			w33.Position = 1;
			w33.Expand = false;
			w33.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.frameCursorPos = new global::Gtk.Frame ();
			this.frameCursorPos.Name = "frameCursorPos";
			// Container child frameCursorPos.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.lbCursorPos = new global::Gtk.Label ();
			this.lbCursorPos.Name = "lbCursorPos";
			this.lbCursorPos.LabelProp = ("0 x 0");
			this.GtkAlignment1.Add (this.lbCursorPos);
			this.frameCursorPos.Add (this.GtkAlignment1);
			this.lbFrameCursorPos = new global::Gtk.Label ();
			this.lbFrameCursorPos.Name = "lbFrameCursorPos";
			this.lbFrameCursorPos.LabelProp = ("<b>Cursor position</b>");
			this.lbFrameCursorPos.UseMarkup = true;
			this.frameCursorPos.LabelWidget = this.lbFrameCursorPos;
			this.vbox1.Add (this.frameCursorPos);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frameCursorPos]));
			w36.Position = 2;
			w36.Expand = false;
			w36.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hboxButtons = new global::Gtk.HBox ();
			this.hboxButtons.Name = "hboxButtons";
			this.hboxButtons.Spacing = 6;
			// Container child hboxButtons.Gtk.Box+BoxChild
			this.btnCancel = new global::Troonie.TroonieButton ();
			this.btnCancel.Name = "btnCancel";
			this.btnCancel.CheckReleaseState = false;
			this.btnCancel.BorderlineWidth = 3;
			this.btnCancel.ButtonHeight = 35;
			this.btnCancel.ButtonWidth = 0;
			this.btnCancel.Font = "Arial";
			this.btnCancel.Text = "Cancel";
			this.btnCancel.TextSize = 14D;
			this.hboxButtons.Add (this.btnCancel);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hboxButtons [this.btnCancel]));
			w37.Position = 0;
			// Container child hboxButtons.Gtk.Box+BoxChild
			this.btnOk = new global::Troonie.TroonieButton ();
			this.btnOk.Name = "btnOk";
			this.btnOk.CheckReleaseState = false;
			this.btnOk.BorderlineWidth = 3;
			this.btnOk.ButtonHeight = 35;
			this.btnOk.ButtonWidth = 0;
			this.btnOk.Font = "Arial";
			this.btnOk.Text = "OK";
			this.btnOk.TextSize = 14D;
			this.hboxButtons.Add (this.btnOk);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hboxButtons [this.btnOk]));
			w38.Position = 1;
			this.vbox1.Add (this.hboxButtons);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hboxButtons]));
			w39.PackType = ((global::Gtk.PackType)(1));
			w39.Position = 3;
			w39.Expand = false;
			w39.Fill = false;
			this.hbox1.Add (this.vbox1);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox1]));
			w40.Position = 1;
			w40.Padding = ((uint)(5));
			this.vboxA.Add (this.hbox1);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vboxA [this.hbox1]));
			w41.Position = 0;
			this.Add (this.vboxA);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 524;
			this.DefaultHeight = 582;
			this.frame_combobox1.Hide ();
			this.frame_combobox2.Hide ();
			this.frame_combobox3.Hide ();
			this.frameComboboxes.Hide ();
			this.frame_hscale1.Hide ();
			this.frame_hscale2.Hide ();
			this.frame_hscale3.Hide ();
			this.frame_hscale4.Hide ();
			this.frame_hscale5.Hide ();
			this.frameHScales.Hide ();
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.checkBtnUse255ForAlpha.Toggled += new global::System.EventHandler (this.OnCheckBtnUse255ForAlphaToggled);
			this.combobox1.Changed += new global::System.EventHandler (this.OnComboboxChanged);
			this.combobox2.Changed += new global::System.EventHandler (this.OnComboboxChanged);
			this.combobox3.Changed += new global::System.EventHandler (this.OnComboboxChanged);
			this.hscale1.ValueChanged += new global::System.EventHandler (this.OnHscaleValueChanged);
			this.hscale2.ValueChanged += new global::System.EventHandler (this.OnHscaleValueChanged);
			this.hscale3.ValueChanged += new global::System.EventHandler (this.OnHscaleValueChanged);
			this.hscale4.ValueChanged += new global::System.EventHandler (this.OnHscaleValueChanged);
			this.hscale5.ValueChanged += new global::System.EventHandler (this.OnHscaleValueChanged);
			this.btnCancel.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnBtnCancelButtonReleaseEvent);
			this.btnOk.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnBtnOkButtonReleaseEvent);
		}
	}
}
