
// This file has been generated by the GUI designer. Do not modify.
namespace Troonie
{
	public partial class StarterWidget
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.HBox hbox1;
		
		private global::Troonie.TroonieButton picBtnConvert;
		
		private global::Troonie.TroonieButton picBtnEdit;
		
		private global::Troonie.TroonieButton picBtnSteganography;
		
		private global::Gtk.HBox hbox2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Troonie.StarterWidget
			global::Stetic.BinContainer.Attach (this);
			this.WidthRequest = 600;
			this.HeightRequest = 150;
			this.CanFocus = true;
			this.Name = "Troonie.StarterWidget";
			// Container child Troonie.StarterWidget.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.BorderWidth = ((uint)(6));
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.picBtnConvert = new global::Troonie.TroonieButton ();
			this.picBtnConvert.Name = "picBtnConvert";
			this.picBtnConvert.CheckReleaseState = false;
			this.picBtnConvert.BorderlineWidth = 3;
			this.picBtnConvert.ButtonHeight = 140;
			this.picBtnConvert.ButtonWidth = 0;
			this.picBtnConvert.Font = "Arial";
			this.picBtnConvert.Text = "Convert";
			this.picBtnConvert.TextSize = 20;
			this.hbox1.Add (this.picBtnConvert);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.picBtnConvert]));
			w1.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.picBtnEdit = new global::Troonie.TroonieButton ();
			this.picBtnEdit.Name = "picBtnEdit";
			this.picBtnEdit.CheckReleaseState = false;
			this.picBtnEdit.BorderlineWidth = 3;
			this.picBtnEdit.ButtonHeight = 140;
			this.picBtnEdit.ButtonWidth = 0;
			this.picBtnEdit.Font = "Arial";
			this.picBtnEdit.Text = "Editor";
			this.picBtnEdit.TextSize = 20;
			this.hbox1.Add (this.picBtnEdit);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.picBtnEdit]));
			w2.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.picBtnSteganography = new global::Troonie.TroonieButton ();
			this.picBtnSteganography.Name = "picBtnSteganography";
			this.picBtnSteganography.CheckReleaseState = false;
			this.picBtnSteganography.BorderlineWidth = 3;
			this.picBtnSteganography.ButtonHeight = 140;
			this.picBtnSteganography.ButtonWidth = 0;
			this.picBtnSteganography.Font = "Arial";
			this.picBtnSteganography.Text = "Steganography";
			this.picBtnSteganography.TextSize = 20;
			this.hbox1.Add (this.picBtnSteganography);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.picBtnSteganography]));
			w3.Position = 2;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w4.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w5.Position = 1;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.picBtnConvert.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnPicBtnConvertButtonReleaseEvent);
			this.picBtnEdit.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnPicBtnEditButtonReleaseEvent);
			this.picBtnSteganography.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnPicBtnSteganographyButtonReleaseEvent);
		}
	}
}
