
// This file has been generated by the GUI designer. Do not modify.
namespace Troonie
{
	public partial class SteganographyWidget
	{
		private global::Gtk.VBox vboxA;
		
		private global::Gtk.EventBox eventboxToolbar;
		
		private global::Gtk.HBox hboxToolbarButtons;
		
		private global::Gtk.HBox hbox1;
		
		private global::Troonie.SimpleImagePanel simpleimagepanel1;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.Frame frameSteganography;
		
		private global::Gtk.Alignment AlignmentFrameSteganography;
		
		private global::Gtk.VBox vboxSteganography;
		
		private global::Gtk.Frame frameProperties;
		
		private global::Gtk.Alignment AlignmentFrameProperties;
		
		private global::Gtk.HBox hboxProperties;
		
		private global::Gtk.Label lbModus;
		
		private global::Gtk.RadioButton rdBtnDecrypt;
		
		private global::Gtk.RadioButton rdBtnEncrypt;
		
		private global::Gtk.VSeparator vseparator1;
		
		private global::Gtk.Label lbPayload;
		
		private global::Gtk.RadioButton rdBtnPayloadText;
		
		private global::Gtk.RadioButton rdBtnPayloadFile;
		
		private global::Gtk.VSeparator vseparator3;
		
		private global::Gtk.Label lbAlgorithm;
		
		private global::Gtk.ComboBox comboboxAlgorithm;
		
		private global::Gtk.CheckButton checkBtnStrongObfuscation;
		
		private global::Gtk.Label lbFrameProperties;
		
		private global::Gtk.Frame frameKey;
		
		private global::Gtk.Alignment AlignmentFrameKey;
		
		private global::Gtk.Entry entryKey;
		
		private global::Gtk.Label lbFrameKey;
		
		private global::Gtk.Frame frameContent;
		
		private global::Gtk.Alignment AlignmentFrameContent;
		
		private global::Gtk.ScrolledWindow scrolledwindowContent;
		
		private global::Gtk.TextView textviewContent;
		
		private global::Gtk.Label lbFrameContent;
		
		private global::Gtk.Frame frameFileChooser;
		
		private global::Gtk.Alignment alignmentFrameFileChooser;
		
		private global::Gtk.HBox hbox2;
		
		private global::Troonie.HyperTextLabel hypertextlabelFileChooser;
		
		private global::Gtk.Entry entryFile;
		
		private global::Gtk.Label lbFrameFileChooser;
		
		private global::Gtk.Label lbFrameSteganography;
		
		private global::Gtk.Frame framePayloadspace;
		
		private global::Gtk.Alignment AlignmentFramePayloadspace;
		
		private global::Gtk.Label lbPayloadspace;
		
		private global::Gtk.Label lbFramePayloadspace;
		
		private global::Troonie.TroonieButton btnOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Troonie.SteganographyWidget
			this.Name = "Troonie.SteganographyWidget";
			this.Title = ("Steganography");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Troonie.SteganographyWidget.Gtk.Container+ContainerChild
			this.vboxA = new global::Gtk.VBox ();
			this.vboxA.Name = "vboxA";
			this.vboxA.Spacing = 6;
			// Container child vboxA.Gtk.Box+BoxChild
			this.eventboxToolbar = new global::Gtk.EventBox ();
			this.eventboxToolbar.Name = "eventboxToolbar";
			// Container child eventboxToolbar.Gtk.Container+ContainerChild
			this.hboxToolbarButtons = new global::Gtk.HBox ();
			this.hboxToolbarButtons.Name = "hboxToolbarButtons";
			this.hboxToolbarButtons.Spacing = 6;
			this.eventboxToolbar.Add (this.hboxToolbarButtons);
			this.vboxA.Add (this.eventboxToolbar);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vboxA [this.eventboxToolbar]));
			w2.Position = 0;
			w2.Expand = false;
			// Container child vboxA.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.simpleimagepanel1 = new global::Troonie.SimpleImagePanel ();
			this.simpleimagepanel1.Events = ((global::Gdk.EventMask)(256));
			this.simpleimagepanel1.Name = "simpleimagepanel1";
			this.simpleimagepanel1.ScaleCursorX = 0F;
			this.simpleimagepanel1.ScaleCursorY = 0F;
			this.hbox1.Add (this.simpleimagepanel1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.simpleimagepanel1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.frameSteganography = new global::Gtk.Frame ();
			this.frameSteganography.Name = "frameSteganography";
			// Container child frameSteganography.Gtk.Container+ContainerChild
			this.AlignmentFrameSteganography = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.AlignmentFrameSteganography.Name = "AlignmentFrameSteganography";
			this.AlignmentFrameSteganography.LeftPadding = ((uint)(12));
			this.AlignmentFrameSteganography.RightPadding = ((uint)(12));
			this.AlignmentFrameSteganography.BottomPadding = ((uint)(12));
			// Container child AlignmentFrameSteganography.Gtk.Container+ContainerChild
			this.vboxSteganography = new global::Gtk.VBox ();
			this.vboxSteganography.Name = "vboxSteganography";
			this.vboxSteganography.Spacing = 6;
			// Container child vboxSteganography.Gtk.Box+BoxChild
			this.frameProperties = new global::Gtk.Frame ();
			this.frameProperties.Name = "frameProperties";
			// Container child frameProperties.Gtk.Container+ContainerChild
			this.AlignmentFrameProperties = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.AlignmentFrameProperties.Name = "AlignmentFrameProperties";
			this.AlignmentFrameProperties.LeftPadding = ((uint)(12));
			// Container child AlignmentFrameProperties.Gtk.Container+ContainerChild
			this.hboxProperties = new global::Gtk.HBox ();
			this.hboxProperties.Name = "hboxProperties";
			this.hboxProperties.Spacing = 6;
			// Container child hboxProperties.Gtk.Box+BoxChild
			this.lbModus = new global::Gtk.Label ();
			this.lbModus.Name = "lbModus";
			this.lbModus.LabelProp = ("<b>Modus</b>");
			this.lbModus.UseMarkup = true;
			this.hboxProperties.Add (this.lbModus);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hboxProperties [this.lbModus]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hboxProperties.Gtk.Box+BoxChild
			this.rdBtnDecrypt = new global::Gtk.RadioButton (("Decrypt"));
			this.rdBtnDecrypt.CanFocus = true;
			this.rdBtnDecrypt.Name = "rdBtnDecrypt";
			this.rdBtnDecrypt.Active = true;
			this.rdBtnDecrypt.DrawIndicator = true;
			this.rdBtnDecrypt.UseUnderline = true;
			this.rdBtnDecrypt.Group = new[] { rdBtnDecrypt }; new global::GLib.SList (global::System.IntPtr.Zero);
			this.hboxProperties.Add (this.rdBtnDecrypt);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hboxProperties [this.rdBtnDecrypt]));
			w5.Position = 1;
			w5.Expand = false;
			// Container child hboxProperties.Gtk.Box+BoxChild
			this.rdBtnEncrypt = new global::Gtk.RadioButton (("Encrypt"));
			this.rdBtnEncrypt.CanFocus = true;
			this.rdBtnEncrypt.Name = "rdBtnEncrypt";
			this.rdBtnEncrypt.DrawIndicator = true;
			this.rdBtnEncrypt.UseUnderline = true;
			this.rdBtnEncrypt.Group = this.rdBtnDecrypt.Group;
			this.hboxProperties.Add (this.rdBtnEncrypt);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hboxProperties [this.rdBtnEncrypt]));
			w6.Position = 2;
			w6.Expand = false;
			// Container child hboxProperties.Gtk.Box+BoxChild
			this.vseparator1 = new global::Gtk.VSeparator ();
			this.vseparator1.Name = "vseparator1";
			this.hboxProperties.Add (this.vseparator1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hboxProperties [this.vseparator1]));
			w7.Position = 3;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hboxProperties.Gtk.Box+BoxChild
			this.lbPayload = new global::Gtk.Label ();
			this.lbPayload.Name = "lbPayload";
			this.lbPayload.LabelProp = ("<b>Payload</b>");
			this.lbPayload.UseMarkup = true;
			this.hboxProperties.Add (this.lbPayload);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hboxProperties [this.lbPayload]));
			w8.Position = 4;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hboxProperties.Gtk.Box+BoxChild
			this.rdBtnPayloadText = new global::Gtk.RadioButton (("Text"));
			this.rdBtnPayloadText.CanFocus = true;
			this.rdBtnPayloadText.Name = "rdBtnPayloadText";
			this.rdBtnPayloadText.Active = true;
			this.rdBtnPayloadText.DrawIndicator = true;
			this.rdBtnPayloadText.UseUnderline = true;
			this.rdBtnPayloadText.Group = new[] { rdBtnPayloadText }; // new global::GLib.SList (global::System.IntPtr.Zero);
			this.hboxProperties.Add (this.rdBtnPayloadText);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hboxProperties [this.rdBtnPayloadText]));
			w9.Position = 5;
			w9.Expand = false;
			// Container child hboxProperties.Gtk.Box+BoxChild
			this.rdBtnPayloadFile = new global::Gtk.RadioButton (("File"));
			this.rdBtnPayloadFile.CanFocus = true;
			this.rdBtnPayloadFile.Name = "rdBtnPayloadFile";
			this.rdBtnPayloadFile.DrawIndicator = true;
			this.rdBtnPayloadFile.UseUnderline = true;
			this.rdBtnPayloadFile.Group = this.rdBtnPayloadText.Group;
			this.hboxProperties.Add (this.rdBtnPayloadFile);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hboxProperties [this.rdBtnPayloadFile]));
			w10.Position = 6;
			w10.Expand = false;
			// Container child hboxProperties.Gtk.Box+BoxChild
			this.vseparator3 = new global::Gtk.VSeparator ();
			this.vseparator3.Name = "vseparator3";
			this.hboxProperties.Add (this.vseparator3);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hboxProperties [this.vseparator3]));
			w11.Position = 7;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hboxProperties.Gtk.Box+BoxChild
			this.lbAlgorithm = new global::Gtk.Label ();
			this.lbAlgorithm.Name = "lbAlgorithm";
			this.lbAlgorithm.LabelProp = ("<b>Algorithm</b>");
			this.lbAlgorithm.UseMarkup = true;
			this.hboxProperties.Add (this.lbAlgorithm);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hboxProperties [this.lbAlgorithm]));
			w12.Position = 8;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hboxProperties.Gtk.Box+BoxChild
			this.comboboxAlgorithm = new Gtk.ComboBox(new[] { "StegHash [2016]", "LeonSteg [2017]", "LeonStegRGB [2017]" });  //( global::Gtk.ComboBox.NewText ();
			//this.comboboxAlgorithm.Add(new Gtk.Widget("StegHash [2016]"));
			//this.comboboxAlgorithm.AppendText (("LeonSteg [2017]"));
			//this.comboboxAlgorithm.AppendText (("LeonStegRGB [2017]"));
			this.comboboxAlgorithm.Name = "comboboxAlgorithm";
			this.comboboxAlgorithm.Active = 1;
			this.hboxProperties.Add (this.comboboxAlgorithm);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hboxProperties [this.comboboxAlgorithm]));
			w13.Position = 9;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hboxProperties.Gtk.Box+BoxChild
			this.checkBtnStrongObfuscation = new global::Gtk.CheckButton ();
			this.checkBtnStrongObfuscation.Sensitive = false;
			this.checkBtnStrongObfuscation.CanFocus = true;
			this.checkBtnStrongObfuscation.Name = "checkBtnStrongObfuscation";
			this.checkBtnStrongObfuscation.Label = ("Strong Obfuscation");
			this.checkBtnStrongObfuscation.DrawIndicator = true;
			this.checkBtnStrongObfuscation.UseUnderline = true;
			this.hboxProperties.Add (this.checkBtnStrongObfuscation);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hboxProperties [this.checkBtnStrongObfuscation]));
			w14.Position = 10;
			w14.Expand = false;
			this.AlignmentFrameProperties.Add (this.hboxProperties);
			this.frameProperties.Add (this.AlignmentFrameProperties);
			this.lbFrameProperties = new global::Gtk.Label ();
			this.lbFrameProperties.Name = "lbFrameProperties";
			this.lbFrameProperties.LabelProp = ("<b>Properties</b>");
			this.lbFrameProperties.UseMarkup = true;
			this.frameProperties.LabelWidget = this.lbFrameProperties;
			this.vboxSteganography.Add (this.frameProperties);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vboxSteganography [this.frameProperties]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vboxSteganography.Gtk.Box+BoxChild
			this.frameKey = new global::Gtk.Frame ();
			this.frameKey.Name = "frameKey";
			// Container child frameKey.Gtk.Container+ContainerChild
			this.AlignmentFrameKey = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.AlignmentFrameKey.Name = "AlignmentFrameKey";
			this.AlignmentFrameKey.LeftPadding = ((uint)(12));
			// Container child AlignmentFrameKey.Gtk.Container+ContainerChild
			this.entryKey = new global::Gtk.Entry ();
			this.entryKey.CanFocus = true;
			this.entryKey.Name = "entryKey";
			this.entryKey.IsEditable = true;
			this.entryKey.MaxLength = 128;
			this.entryKey.Visibility = false;
			this.entryKey.InvisibleChar = '●';
			this.AlignmentFrameKey.Add (this.entryKey);
			this.frameKey.Add (this.AlignmentFrameKey);
			this.lbFrameKey = new global::Gtk.Label ();
			this.lbFrameKey.Name = "lbFrameKey";
			this.lbFrameKey.LabelProp = ("<b>Key</b>");
			this.lbFrameKey.UseMarkup = true;
			this.frameKey.LabelWidget = this.lbFrameKey;
			this.vboxSteganography.Add (this.frameKey);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vboxSteganography [this.frameKey]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vboxSteganography.Gtk.Box+BoxChild
			this.frameContent = new global::Gtk.Frame ();
			this.frameContent.Name = "frameContent";
			// Container child frameContent.Gtk.Container+ContainerChild
			this.AlignmentFrameContent = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.AlignmentFrameContent.Name = "AlignmentFrameContent";
			this.AlignmentFrameContent.LeftPadding = ((uint)(12));
			// Container child AlignmentFrameContent.Gtk.Container+ContainerChild
			this.scrolledwindowContent = new global::Gtk.ScrolledWindow ();
			this.scrolledwindowContent.CanFocus = true;
			this.scrolledwindowContent.Name = "scrolledwindowContent";
			this.scrolledwindowContent.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindowContent.Gtk.Container+ContainerChild
			this.textviewContent = new global::Gtk.TextView ();
			this.textviewContent.Buffer.Text = "Testtext";
			this.textviewContent.CanFocus = true;
			this.textviewContent.Name = "textviewContent";
			this.scrolledwindowContent.Add (this.textviewContent);
			this.AlignmentFrameContent.Add (this.scrolledwindowContent);
			this.frameContent.Add (this.AlignmentFrameContent);
			this.lbFrameContent = new global::Gtk.Label ();
			this.lbFrameContent.Name = "lbFrameContent";
			this.lbFrameContent.LabelProp = ("<b>Content</b>");
			this.lbFrameContent.UseMarkup = true;
			this.frameContent.LabelWidget = this.lbFrameContent;
			this.vboxSteganography.Add (this.frameContent);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vboxSteganography [this.frameContent]));
			w24.Position = 2;
			// Container child vboxSteganography.Gtk.Box+BoxChild
			this.frameFileChooser = new global::Gtk.Frame ();
			this.frameFileChooser.Name = "frameFileChooser";
			// Container child frameFileChooser.Gtk.Container+ContainerChild
			this.alignmentFrameFileChooser = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.alignmentFrameFileChooser.Name = "alignmentFrameFileChooser";
			this.alignmentFrameFileChooser.LeftPadding = ((uint)(12));
			// Container child alignmentFrameFileChooser.Gtk.Container+ContainerChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.hypertextlabelFileChooser = new global::Troonie.HyperTextLabel ();
			this.hypertextlabelFileChooser.HeightRequest = 5;
			this.hypertextlabelFileChooser.Sensitive = false;
			this.hypertextlabelFileChooser.Name = "hypertextlabelFileChooser";
			this.hypertextlabelFileChooser.Sensitive = false;
			this.hypertextlabelFileChooser.Font = "Arial";
			this.hypertextlabelFileChooser.Text = "Please choose file";
			this.hypertextlabelFileChooser.TextSize = 10;
			this.hypertextlabelFileChooser.ShownTextLength = 30;
			this.hypertextlabelFileChooser.Underline = false;
			this.hypertextlabelFileChooser.Bold = true;
			this.hypertextlabelFileChooser.Italic = false;
			this.hbox2.Add (this.hypertextlabelFileChooser);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.hypertextlabelFileChooser]));
			w25.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.entryFile = new global::Gtk.Entry ();
			this.entryFile.CanFocus = true;
			this.entryFile.Name = "entryFile";
			this.entryFile.Text = ("result.txt");
			this.entryFile.IsEditable = true;
			this.entryFile.InvisibleChar = '●';
			this.hbox2.Add (this.entryFile);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.entryFile]));
			w26.Position = 1;
			this.alignmentFrameFileChooser.Add (this.hbox2);
			this.frameFileChooser.Add (this.alignmentFrameFileChooser);
			this.lbFrameFileChooser = new global::Gtk.Label ();
			this.lbFrameFileChooser.Name = "lbFrameFileChooser";
			this.lbFrameFileChooser.LabelProp = ("<b>File</b>");
			this.lbFrameFileChooser.UseMarkup = true;
			this.frameFileChooser.LabelWidget = this.lbFrameFileChooser;
			this.vboxSteganography.Add (this.frameFileChooser);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vboxSteganography [this.frameFileChooser]));
			w29.Position = 3;
			w29.Expand = false;
			w29.Fill = false;
			this.AlignmentFrameSteganography.Add (this.vboxSteganography);
			this.frameSteganography.Add (this.AlignmentFrameSteganography);
			this.lbFrameSteganography = new global::Gtk.Label ();
			this.lbFrameSteganography.Name = "lbFrameSteganography";
			this.lbFrameSteganography.LabelProp = ("<b>Steganography</b>");
			this.lbFrameSteganography.UseMarkup = true;
			this.frameSteganography.LabelWidget = this.lbFrameSteganography;
			this.vbox1.Add (this.frameSteganography);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frameSteganography]));
			w32.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.framePayloadspace = new global::Gtk.Frame ();
			this.framePayloadspace.Name = "framePayloadspace";
			// Container child framePayloadspace.Gtk.Container+ContainerChild
			this.AlignmentFramePayloadspace = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.AlignmentFramePayloadspace.Name = "AlignmentFramePayloadspace";
			this.AlignmentFramePayloadspace.LeftPadding = ((uint)(12));
			// Container child AlignmentFramePayloadspace.Gtk.Container+ContainerChild
			this.lbPayloadspace = new global::Gtk.Label ();
			this.lbPayloadspace.Name = "lbPayloadspace";
			this.lbPayloadspace.LabelProp = ("0 x 0");
			this.AlignmentFramePayloadspace.Add (this.lbPayloadspace);
			this.framePayloadspace.Add (this.AlignmentFramePayloadspace);
			this.lbFramePayloadspace = new global::Gtk.Label ();
			this.lbFramePayloadspace.Name = "lbFramePayloadspace";
			this.lbFramePayloadspace.LabelProp = ("<b>Payloadspace</b>");
			this.lbFramePayloadspace.UseMarkup = true;
			this.framePayloadspace.LabelWidget = this.lbFramePayloadspace;
			this.vbox1.Add (this.framePayloadspace);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.framePayloadspace]));
			w35.Position = 1;
			w35.Expand = false;
			w35.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.btnOk = new global::Troonie.TroonieButton ();
			this.btnOk.Name = "btnOk";
			this.btnOk.CheckReleaseState = false;
			this.btnOk.BorderlineWidth = 3;
			this.btnOk.ButtonHeight = 35;
			this.btnOk.ButtonWidth = 0;
			this.btnOk.Font = "Arial";
			this.btnOk.Text = "OK";
			this.btnOk.TextSize = 14D;
			this.vbox1.Add (this.btnOk);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.btnOk]));
			w36.Position = 2;
			w36.Expand = false;
			w36.Fill = false;
			this.hbox1.Add (this.vbox1);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox1]));
			w37.Position = 1;
			w37.Padding = ((uint)(5));
			this.vboxA.Add (this.hbox1);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vboxA [this.hbox1]));
			w38.Position = 1;
			this.Add (this.vboxA);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 1021;
			this.DefaultHeight = 534;
			this.checkBtnStrongObfuscation.Hide ();
			this.frameFileChooser.Hide ();
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.DragDrop += new global::Gtk.DragDropHandler (this.OnDragDrop);
			this.DragDataReceived += new global::Gtk.DragDataReceivedHandler (this.OnDragDataReceived);
			this.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.OnKeyPressEvent);
			this.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler (this.OnKeyReleaseEvent);
			this.rdBtnEncrypt.Toggled += new global::System.EventHandler (this.OnRdBtnEncryptToggled);
			this.rdBtnPayloadText.Toggled += new global::System.EventHandler (this.OnComboboxAlgorithmChanged);
			this.rdBtnPayloadFile.Toggled += new global::System.EventHandler (this.OnComboboxAlgorithmChanged);
			this.comboboxAlgorithm.Changed += new global::System.EventHandler (this.OnComboboxAlgorithmChanged);
			this.entryKey.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler (this.OnEntryKeyKeyReleaseEvent);
			this.btnOk.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnBtnOkButtonReleaseEvent);
		}
	}
}
