
// This file has been generated by the GUI designer. Do not modify.
namespace Troonie
{
	public partial class OptionsWidget
	{
		private global::Gtk.ScrolledWindow scrolledwindow1;
		
		private global::Gtk.EventBox eventbox1;
		
		private global::Gtk.Notebook notebook1;
		
		private global::Gtk.EventBox eventboxPage1;
		
		private global::Gtk.VBox vboxPage1;
		
		private global::Gtk.Frame frameAskForDesktopContextMenu;
		
		private global::Gtk.Alignment AlignmentDesktopContextMenu;
		
		private global::Gtk.HBox hboxDesktopContextMenu;
		
		private global::Gtk.CheckButton checkBtnDesktopContextMenu;
		
		private global::Gtk.Label lbFrameDesktopContextMenu;
		
		private global::Gtk.Frame frameVipSize;
		
		private global::Gtk.Alignment AlignmentVipSize;
		
		private global::Gtk.HBox hboxVipSize;
		
		private global::Troonie.TroonieButton btnPlusVipSize;
		
		private global::Gtk.Entry entryVipSize;
		
		private global::Troonie.TroonieButton btnMinusVipSize;
		
		private global::Gtk.Label lbVipSize;
		
		private global::Gtk.Frame frameMaxSideLengthFilterImage;
		
		private global::Gtk.Alignment AlignmentMaxSideLengthFilterImage;
		
		private global::Gtk.HBox hboxMaxSideLengthFilterImage;
		
		private global::Troonie.TroonieButton btnPlusMaxSideLengthFilterImage;
		
		private global::Gtk.Entry entryMaxSideLengthFilterImage;
		
		private global::Troonie.TroonieButton btnMinusMaxSideLengthFilterImage;
		
		private global::Gtk.Label lbMaxSideLengthFilterImage;
		
		private global::Gtk.Frame frameVideoplayer;
		
		private global::Gtk.Alignment AlignmentVideoplayer;
		
		private global::Gtk.HBox hboxVideoplayer;
		
		private global::Troonie.HyperTextLabel hypertextlabelVideoplayer;
		
		private global::Gtk.Label lbFrameVideoplayer;
		
		private global::Gtk.Frame frameKeywordsXmlFile;
		
		private global::Gtk.Alignment AlignmentKeywordsXmlFile;
		
		private global::Gtk.HBox hboxKeywordsXmlFile;
		
		private global::Troonie.HyperTextLabel hypertextlabelKeywordsXmlFile;
		
		private global::Gtk.Label lbFrameKeywordsXmlFile;
		
		private global::Gtk.Label lbPage1;
		
		private global::Gtk.EventBox eventboxPage2;
		
		private global::Gtk.Table table1;
		
		private global::Gtk.Label lbPage2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Troonie.OptionsWidget
			this.Name = "Troonie.OptionsWidget";
			this.Title = global::Mono.Unix.Catalog.GetString ("OptionsWidget");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Troonie.OptionsWidget.Gtk.Container+ContainerChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(3));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			global::Gtk.Viewport w1 = new global::Gtk.Viewport ();
			w1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.eventbox1 = new global::Gtk.EventBox ();
			this.eventbox1.Name = "eventbox1";
			// Container child eventbox1.Gtk.Container+ContainerChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 0;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.eventboxPage1 = new global::Gtk.EventBox ();
			this.eventboxPage1.Name = "eventboxPage1";
			// Container child eventboxPage1.Gtk.Container+ContainerChild
			this.vboxPage1 = new global::Gtk.VBox ();
			this.vboxPage1.Name = "vboxPage1";
			this.vboxPage1.Spacing = 6;
			// Container child vboxPage1.Gtk.Box+BoxChild
			this.frameAskForDesktopContextMenu = new global::Gtk.Frame ();
			this.frameAskForDesktopContextMenu.Name = "frameAskForDesktopContextMenu";
			this.frameAskForDesktopContextMenu.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frameAskForDesktopContextMenu.Gtk.Container+ContainerChild
			this.AlignmentDesktopContextMenu = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.AlignmentDesktopContextMenu.Name = "AlignmentDesktopContextMenu";
			this.AlignmentDesktopContextMenu.LeftPadding = ((uint)(12));
			// Container child AlignmentDesktopContextMenu.Gtk.Container+ContainerChild
			this.hboxDesktopContextMenu = new global::Gtk.HBox ();
			this.hboxDesktopContextMenu.Name = "hboxDesktopContextMenu";
			this.hboxDesktopContextMenu.Spacing = 6;
			// Container child hboxDesktopContextMenu.Gtk.Box+BoxChild
			this.checkBtnDesktopContextMenu = new global::Gtk.CheckButton ();
			this.checkBtnDesktopContextMenu.CanFocus = true;
			this.checkBtnDesktopContextMenu.Name = "checkBtnDesktopContextMenu";
			this.checkBtnDesktopContextMenu.Label = global::Mono.Unix.Catalog.GetString ("checkBtnDesktopContextMenu");
			this.checkBtnDesktopContextMenu.DrawIndicator = true;
			this.checkBtnDesktopContextMenu.UseUnderline = true;
			this.hboxDesktopContextMenu.Add (this.checkBtnDesktopContextMenu);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hboxDesktopContextMenu [this.checkBtnDesktopContextMenu]));
			w2.Position = 0;
			this.AlignmentDesktopContextMenu.Add (this.hboxDesktopContextMenu);
			this.frameAskForDesktopContextMenu.Add (this.AlignmentDesktopContextMenu);
			this.lbFrameDesktopContextMenu = new global::Gtk.Label ();
			this.lbFrameDesktopContextMenu.Name = "lbFrameDesktopContextMenu";
			this.lbFrameDesktopContextMenu.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>lbKDesktopContextMenu</b>");
			this.lbFrameDesktopContextMenu.UseMarkup = true;
			this.frameAskForDesktopContextMenu.LabelWidget = this.lbFrameDesktopContextMenu;
			this.vboxPage1.Add (this.frameAskForDesktopContextMenu);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vboxPage1 [this.frameAskForDesktopContextMenu]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vboxPage1.Gtk.Box+BoxChild
			this.frameVipSize = new global::Gtk.Frame ();
			this.frameVipSize.Name = "frameVipSize";
			this.frameVipSize.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frameVipSize.Gtk.Container+ContainerChild
			this.AlignmentVipSize = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.AlignmentVipSize.Name = "AlignmentVipSize";
			this.AlignmentVipSize.LeftPadding = ((uint)(12));
			// Container child AlignmentVipSize.Gtk.Container+ContainerChild
			this.hboxVipSize = new global::Gtk.HBox ();
			this.hboxVipSize.Name = "hboxVipSize";
			this.hboxVipSize.Spacing = 6;
			// Container child hboxVipSize.Gtk.Box+BoxChild
			this.btnPlusVipSize = new global::Troonie.TroonieButton ();
			this.btnPlusVipSize.Name = "btnPlusVipSize";
			this.btnPlusVipSize.CheckReleaseState = true;
			this.btnPlusVipSize.BorderlineWidth = 2;
			this.btnPlusVipSize.ButtonHeight = 35;
			this.btnPlusVipSize.ButtonWidth = 0;
			this.btnPlusVipSize.Font = "Arial";
			this.btnPlusVipSize.Text = "+";
			this.btnPlusVipSize.TextSize = 12D;
			this.hboxVipSize.Add (this.btnPlusVipSize);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hboxVipSize [this.btnPlusVipSize]));
			w6.Position = 0;
			// Container child hboxVipSize.Gtk.Box+BoxChild
			this.entryVipSize = new global::Gtk.Entry ();
			this.entryVipSize.CanFocus = true;
			this.entryVipSize.Name = "entryVipSize";
			this.entryVipSize.IsEditable = true;
			this.entryVipSize.InvisibleChar = '●';
			this.hboxVipSize.Add (this.entryVipSize);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hboxVipSize [this.entryVipSize]));
			w7.Position = 1;
			// Container child hboxVipSize.Gtk.Box+BoxChild
			this.btnMinusVipSize = new global::Troonie.TroonieButton ();
			this.btnMinusVipSize.Name = "btnMinusVipSize";
			this.btnMinusVipSize.CheckReleaseState = true;
			this.btnMinusVipSize.BorderlineWidth = 2;
			this.btnMinusVipSize.ButtonHeight = 35;
			this.btnMinusVipSize.ButtonWidth = 0;
			this.btnMinusVipSize.Font = "Arial";
			this.btnMinusVipSize.Text = "-";
			this.btnMinusVipSize.TextSize = 12D;
			this.hboxVipSize.Add (this.btnMinusVipSize);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hboxVipSize [this.btnMinusVipSize]));
			w8.Position = 2;
			this.AlignmentVipSize.Add (this.hboxVipSize);
			this.frameVipSize.Add (this.AlignmentVipSize);
			this.lbVipSize = new global::Gtk.Label ();
			this.lbVipSize.Name = "lbVipSize";
			this.lbVipSize.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>lbVipSize</b>");
			this.lbVipSize.UseMarkup = true;
			this.frameVipSize.LabelWidget = this.lbVipSize;
			this.vboxPage1.Add (this.frameVipSize);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vboxPage1 [this.frameVipSize]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vboxPage1.Gtk.Box+BoxChild
			this.frameMaxSideLengthFilterImage = new global::Gtk.Frame ();
			this.frameMaxSideLengthFilterImage.Name = "frameMaxSideLengthFilterImage";
			this.frameMaxSideLengthFilterImage.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frameMaxSideLengthFilterImage.Gtk.Container+ContainerChild
			this.AlignmentMaxSideLengthFilterImage = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.AlignmentMaxSideLengthFilterImage.Name = "AlignmentMaxSideLengthFilterImage";
			this.AlignmentMaxSideLengthFilterImage.LeftPadding = ((uint)(12));
			// Container child AlignmentMaxSideLengthFilterImage.Gtk.Container+ContainerChild
			this.hboxMaxSideLengthFilterImage = new global::Gtk.HBox ();
			this.hboxMaxSideLengthFilterImage.Name = "hboxMaxSideLengthFilterImage";
			this.hboxMaxSideLengthFilterImage.Spacing = 6;
			// Container child hboxMaxSideLengthFilterImage.Gtk.Box+BoxChild
			this.btnPlusMaxSideLengthFilterImage = new global::Troonie.TroonieButton ();
			this.btnPlusMaxSideLengthFilterImage.Name = "btnPlusMaxSideLengthFilterImage";
			this.btnPlusMaxSideLengthFilterImage.CheckReleaseState = true;
			this.btnPlusMaxSideLengthFilterImage.BorderlineWidth = 2;
			this.btnPlusMaxSideLengthFilterImage.ButtonHeight = 35;
			this.btnPlusMaxSideLengthFilterImage.ButtonWidth = 0;
			this.btnPlusMaxSideLengthFilterImage.Font = "Arial";
			this.btnPlusMaxSideLengthFilterImage.Text = "+";
			this.btnPlusMaxSideLengthFilterImage.TextSize = 12D;
			this.hboxMaxSideLengthFilterImage.Add (this.btnPlusMaxSideLengthFilterImage);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hboxMaxSideLengthFilterImage [this.btnPlusMaxSideLengthFilterImage]));
			w12.Position = 0;
			// Container child hboxMaxSideLengthFilterImage.Gtk.Box+BoxChild
			this.entryMaxSideLengthFilterImage = new global::Gtk.Entry ();
			this.entryMaxSideLengthFilterImage.CanFocus = true;
			this.entryMaxSideLengthFilterImage.Name = "entryMaxSideLengthFilterImage";
			this.entryMaxSideLengthFilterImage.IsEditable = true;
			this.entryMaxSideLengthFilterImage.InvisibleChar = '●';
			this.hboxMaxSideLengthFilterImage.Add (this.entryMaxSideLengthFilterImage);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hboxMaxSideLengthFilterImage [this.entryMaxSideLengthFilterImage]));
			w13.Position = 1;
			// Container child hboxMaxSideLengthFilterImage.Gtk.Box+BoxChild
			this.btnMinusMaxSideLengthFilterImage = new global::Troonie.TroonieButton ();
			this.btnMinusMaxSideLengthFilterImage.Name = "btnMinusMaxSideLengthFilterImage";
			this.btnMinusMaxSideLengthFilterImage.CheckReleaseState = true;
			this.btnMinusMaxSideLengthFilterImage.BorderlineWidth = 2;
			this.btnMinusMaxSideLengthFilterImage.ButtonHeight = 35;
			this.btnMinusMaxSideLengthFilterImage.ButtonWidth = 0;
			this.btnMinusMaxSideLengthFilterImage.Font = "Arial";
			this.btnMinusMaxSideLengthFilterImage.Text = "-";
			this.btnMinusMaxSideLengthFilterImage.TextSize = 12D;
			this.hboxMaxSideLengthFilterImage.Add (this.btnMinusMaxSideLengthFilterImage);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hboxMaxSideLengthFilterImage [this.btnMinusMaxSideLengthFilterImage]));
			w14.Position = 2;
			this.AlignmentMaxSideLengthFilterImage.Add (this.hboxMaxSideLengthFilterImage);
			this.frameMaxSideLengthFilterImage.Add (this.AlignmentMaxSideLengthFilterImage);
			this.lbMaxSideLengthFilterImage = new global::Gtk.Label ();
			this.lbMaxSideLengthFilterImage.Name = "lbMaxSideLengthFilterImage";
			this.lbMaxSideLengthFilterImage.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>lbMaxSideLengthFilterImage</b>");
			this.lbMaxSideLengthFilterImage.UseMarkup = true;
			this.frameMaxSideLengthFilterImage.LabelWidget = this.lbMaxSideLengthFilterImage;
			this.vboxPage1.Add (this.frameMaxSideLengthFilterImage);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vboxPage1 [this.frameMaxSideLengthFilterImage]));
			w17.Position = 3;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vboxPage1.Gtk.Box+BoxChild
			this.frameVideoplayer = new global::Gtk.Frame ();
			this.frameVideoplayer.Name = "frameVideoplayer";
			this.frameVideoplayer.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frameVideoplayer.Gtk.Container+ContainerChild
			this.AlignmentVideoplayer = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.AlignmentVideoplayer.Name = "AlignmentVideoplayer";
			this.AlignmentVideoplayer.LeftPadding = ((uint)(12));
			// Container child AlignmentVideoplayer.Gtk.Container+ContainerChild
			this.hboxVideoplayer = new global::Gtk.HBox ();
			this.hboxVideoplayer.Name = "hboxVideoplayer";
			this.hboxVideoplayer.Spacing = 6;
			// Container child hboxVideoplayer.Gtk.Box+BoxChild
			this.hypertextlabelVideoplayer = new global::Troonie.HyperTextLabel ();
			this.hypertextlabelVideoplayer.Sensitive = false;
			this.hypertextlabelVideoplayer.Name = "hypertextlabelVideoplayer";
			this.hypertextlabelVideoplayer.Sensitive = false;
			this.hypertextlabelVideoplayer.Text = "Starttext";
			this.hypertextlabelVideoplayer.TextSize = 0;
			this.hypertextlabelVideoplayer.ShownTextLength = 0;
			this.hypertextlabelVideoplayer.Underline = false;
			this.hypertextlabelVideoplayer.Bold = false;
			this.hypertextlabelVideoplayer.Italic = false;
			this.hboxVideoplayer.Add (this.hypertextlabelVideoplayer);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hboxVideoplayer [this.hypertextlabelVideoplayer]));
			w18.Position = 0;
			this.AlignmentVideoplayer.Add (this.hboxVideoplayer);
			this.frameVideoplayer.Add (this.AlignmentVideoplayer);
			this.lbFrameVideoplayer = new global::Gtk.Label ();
			this.lbFrameVideoplayer.Name = "lbFrameVideoplayer";
			this.lbFrameVideoplayer.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>lbFrameVideoplayer</b>");
			this.lbFrameVideoplayer.UseMarkup = true;
			this.frameVideoplayer.LabelWidget = this.lbFrameVideoplayer;
			this.vboxPage1.Add (this.frameVideoplayer);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vboxPage1 [this.frameVideoplayer]));
			w21.Position = 4;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vboxPage1.Gtk.Box+BoxChild
			this.frameKeywordsXmlFile = new global::Gtk.Frame ();
			this.frameKeywordsXmlFile.Name = "frameKeywordsXmlFile";
			this.frameKeywordsXmlFile.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frameKeywordsXmlFile.Gtk.Container+ContainerChild
			this.AlignmentKeywordsXmlFile = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.AlignmentKeywordsXmlFile.Name = "AlignmentKeywordsXmlFile";
			this.AlignmentKeywordsXmlFile.LeftPadding = ((uint)(12));
			// Container child AlignmentKeywordsXmlFile.Gtk.Container+ContainerChild
			this.hboxKeywordsXmlFile = new global::Gtk.HBox ();
			this.hboxKeywordsXmlFile.Name = "hboxKeywordsXmlFile";
			this.hboxKeywordsXmlFile.Spacing = 6;
			// Container child hboxKeywordsXmlFile.Gtk.Box+BoxChild
			this.hypertextlabelKeywordsXmlFile = new global::Troonie.HyperTextLabel ();
			this.hypertextlabelKeywordsXmlFile.Sensitive = false;
			this.hypertextlabelKeywordsXmlFile.Name = "hypertextlabelKeywordsXmlFile";
			this.hypertextlabelKeywordsXmlFile.Sensitive = false;
			this.hypertextlabelKeywordsXmlFile.Text = "Starttext";
			this.hypertextlabelKeywordsXmlFile.TextSize = 0;
			this.hypertextlabelKeywordsXmlFile.ShownTextLength = 0;
			this.hypertextlabelKeywordsXmlFile.Underline = false;
			this.hypertextlabelKeywordsXmlFile.Bold = false;
			this.hypertextlabelKeywordsXmlFile.Italic = false;
			this.hboxKeywordsXmlFile.Add (this.hypertextlabelKeywordsXmlFile);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hboxKeywordsXmlFile [this.hypertextlabelKeywordsXmlFile]));
			w22.Position = 0;
			this.AlignmentKeywordsXmlFile.Add (this.hboxKeywordsXmlFile);
			this.frameKeywordsXmlFile.Add (this.AlignmentKeywordsXmlFile);
			this.lbFrameKeywordsXmlFile = new global::Gtk.Label ();
			this.lbFrameKeywordsXmlFile.Name = "lbFrameKeywordsXmlFile";
			this.lbFrameKeywordsXmlFile.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>lbKeywordsXmlFile</b>");
			this.lbFrameKeywordsXmlFile.UseMarkup = true;
			this.frameKeywordsXmlFile.LabelWidget = this.lbFrameKeywordsXmlFile;
			this.vboxPage1.Add (this.frameKeywordsXmlFile);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vboxPage1 [this.frameKeywordsXmlFile]));
			w25.Position = 5;
			w25.Expand = false;
			w25.Fill = false;
			this.eventboxPage1.Add (this.vboxPage1);
			this.notebook1.Add (this.eventboxPage1);
			// Notebook tab
			this.lbPage1 = new global::Gtk.Label ();
			this.lbPage1.Name = "lbPage1";
			this.lbPage1.LabelProp = global::Mono.Unix.Catalog.GetString ("lbPage1");
			this.notebook1.SetTabLabel (this.eventboxPage1, this.lbPage1);
			this.lbPage1.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.eventboxPage2 = new global::Gtk.EventBox ();
			this.eventboxPage2.Name = "eventboxPage2";
			// Container child eventboxPage2.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			this.eventboxPage2.Add (this.table1);
			this.notebook1.Add (this.eventboxPage2);
			global::Gtk.Notebook.NotebookChild w29 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.eventboxPage2]));
			w29.Position = 1;
			// Notebook tab
			this.lbPage2 = new global::Gtk.Label ();
			this.lbPage2.Name = "lbPage2";
			this.lbPage2.LabelProp = global::Mono.Unix.Catalog.GetString ("lbPage2");
			this.notebook1.SetTabLabel (this.eventboxPage2, this.lbPage2);
			this.lbPage2.ShowAll ();
			this.eventbox1.Add (this.notebook1);
			w1.Add (this.eventbox1);
			this.scrolledwindow1.Add (w1);
			this.Add (this.scrolledwindow1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.checkBtnDesktopContextMenu.Toggled += new global::System.EventHandler (this.OnCheckBtnDesktopContextMenuToggled);
			this.btnPlusVipSize.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnButtonReleaseEvent);
			this.btnPlusVipSize.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnBtnVipSizePressEvent);
			this.entryVipSize.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler (this.OnEntryVipSizeKeyReleaseEvent);
			this.btnMinusVipSize.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnButtonReleaseEvent);
			this.btnMinusVipSize.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnBtnVipSizePressEvent);
			this.btnPlusMaxSideLengthFilterImage.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnButtonReleaseEvent);
			this.btnPlusMaxSideLengthFilterImage.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnBtnMaxSideLengthFilterImagePressEvent);
			this.entryMaxSideLengthFilterImage.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler (this.OnEntryMaxSideLengthFilterImageKeyReleaseEvent);
			this.btnMinusMaxSideLengthFilterImage.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnButtonReleaseEvent);
			this.btnMinusMaxSideLengthFilterImage.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnBtnMaxSideLengthFilterImagePressEvent);
		}
	}
}
