
// This file has been generated by the GUI designer. Do not modify.
namespace Troonie
{
	public partial class ViewerImagePanel
	{
		private global::Gtk.VBox vboxA;
		
		private global::Troonie.SimpleImagePanel simpleimagepanel;
		
		private global::Gtk.Label lbRating;
		
		private global::Gtk.Label lbTags;
		
		private global::Gtk.Label lbAdditionalInfos;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Troonie.ViewerImagePanel
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Troonie.ViewerImagePanel";
			// Container child Troonie.ViewerImagePanel.Gtk.Container+ContainerChild
			this.vboxA = new global::Gtk.VBox ();
			this.vboxA.Name = "vboxA";
			this.vboxA.Spacing = 6;
			// Container child vboxA.Gtk.Box+BoxChild
			this.simpleimagepanel = new global::Troonie.SimpleImagePanel ();
			this.simpleimagepanel.Events = ((global::Gdk.EventMask)(256));
			this.simpleimagepanel.Name = "simpleimagepanel";
			this.simpleimagepanel.ScaleCursorX = 0F;
			this.simpleimagepanel.ScaleCursorY = 0F;
			this.vboxA.Add (this.simpleimagepanel);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vboxA [this.simpleimagepanel]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vboxA.Gtk.Box+BoxChild
			this.lbRating = new global::Gtk.Label ();
			this.lbRating.Name = "lbRating";
			this.lbRating.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>lbRating</b>");
			this.lbRating.UseMarkup = true;
			this.vboxA.Add (this.lbRating);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vboxA [this.lbRating]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vboxA.Gtk.Box+BoxChild
			this.lbTags = new global::Gtk.Label ();
			this.lbTags.Name = "lbTags";
			this.lbTags.LabelProp = global::Mono.Unix.Catalog.GetString ("Tag1a, Tag1b, Tag1c,\nTag2a, Tag2b");
			this.vboxA.Add (this.lbTags);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vboxA [this.lbTags]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vboxA.Gtk.Box+BoxChild
			this.lbAdditionalInfos = new global::Gtk.Label ();
			this.lbAdditionalInfos.Name = "lbAdditionalInfos";
			this.lbAdditionalInfos.LabelProp = global::Mono.Unix.Catalog.GetString ("lbAdditionalInfos");
			this.vboxA.Add (this.lbAdditionalInfos);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vboxA [this.lbAdditionalInfos]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			this.Add (this.vboxA);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
