
// This file has been generated by the GUI designer. Do not modify.
namespace Troonie
{
	public partial class ViewerWidget
	{
		private global::Gtk.VBox vboxA;
		
		private global::Gtk.EventBox eventboxToolbar;
		
		private global::Gtk.HBox hboxToolbarButtons;
		
		private global::Gtk.HBox hboxViewerAndMenu;
		
		private global::Gtk.ScrolledWindow scrolledwindowViewer;
		
		private global::Gtk.Table tableViewer;
		
		private global::Gtk.VBox vboxMenu;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Troonie.ViewerWidget
			this.Name = "Troonie.ViewerWidget";
			this.Title = global::Mono.Unix.Catalog.GetString ("ViewerWidget");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Troonie.ViewerWidget.Gtk.Container+ContainerChild
			this.vboxA = new global::Gtk.VBox ();
			this.vboxA.Name = "vboxA";
			this.vboxA.Spacing = 6;
			// Container child vboxA.Gtk.Box+BoxChild
			this.eventboxToolbar = new global::Gtk.EventBox ();
			this.eventboxToolbar.Name = "eventboxToolbar";
			// Container child eventboxToolbar.Gtk.Container+ContainerChild
			this.hboxToolbarButtons = new global::Gtk.HBox ();
			this.hboxToolbarButtons.Name = "hboxToolbarButtons";
			this.hboxToolbarButtons.Spacing = 6;
			this.eventboxToolbar.Add (this.hboxToolbarButtons);
			this.vboxA.Add (this.eventboxToolbar);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vboxA [this.eventboxToolbar]));
			w2.Position = 0;
			w2.Expand = false;
			// Container child vboxA.Gtk.Box+BoxChild
			this.hboxViewerAndMenu = new global::Gtk.HBox ();
			this.hboxViewerAndMenu.Name = "hboxViewerAndMenu";
			this.hboxViewerAndMenu.Spacing = 6;
			// Container child hboxViewerAndMenu.Gtk.Box+BoxChild
			this.scrolledwindowViewer = new global::Gtk.ScrolledWindow ();
			this.scrolledwindowViewer.CanFocus = true;
			this.scrolledwindowViewer.Name = "scrolledwindowViewer";
			this.scrolledwindowViewer.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindowViewer.Gtk.Container+ContainerChild
			global::Gtk.Viewport w3 = new global::Gtk.Viewport ();
			w3.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.tableViewer = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
			this.tableViewer.Name = "tableViewer";
			this.tableViewer.RowSpacing = ((uint)(6));
			this.tableViewer.ColumnSpacing = ((uint)(6));
			w3.Add (this.tableViewer);
			this.scrolledwindowViewer.Add (w3);
			this.hboxViewerAndMenu.Add (this.scrolledwindowViewer);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hboxViewerAndMenu [this.scrolledwindowViewer]));
			w6.Position = 0;
			// Container child hboxViewerAndMenu.Gtk.Box+BoxChild
			this.vboxMenu = new global::Gtk.VBox ();
			this.vboxMenu.Name = "vboxMenu";
			this.vboxMenu.Spacing = 6;
			this.hboxViewerAndMenu.Add (this.vboxMenu);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hboxViewerAndMenu [this.vboxMenu]));
			w7.Position = 1;
			this.vboxA.Add (this.hboxViewerAndMenu);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vboxA [this.hboxViewerAndMenu]));
			w8.Position = 1;
			this.Add (this.vboxA);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		}
	}
}
