
// This file has been generated by the GUI designer. Do not modify.
namespace Troonie
{
	public partial class ImagePanel
	{
		private global::Gtk.Fixed fixed1;
		private global::Gtk.DrawingArea drawingAreaImage;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Troonie.ImagePanel
			global::Stetic.BinContainer.Attach (this);
			this.Events = ((global::Gdk.EventMask)(1024));
			this.Name = "Troonie.ImagePanel";
			// Container child Troonie.ImagePanel.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.drawingAreaImage = new global::Gtk.DrawingArea ();
			this.drawingAreaImage.CanFocus = true;
			this.drawingAreaImage.Events = ((global::Gdk.EventMask)(772));
			this.drawingAreaImage.Name = "drawingAreaImage";
			this.fixed1.Add (this.drawingAreaImage);
			this.Add (this.fixed1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.drawingAreaImage.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnDrawingAreaImageExposeEvent);
			this.drawingAreaImage.MotionNotifyEvent += new global::Gtk.MotionNotifyEventHandler (this.OnDrawingAreaImageMotionNotifyEvent);
			this.drawingAreaImage.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnDrawingAreaImageButtonPressEvent);
			this.drawingAreaImage.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnDrawingAreaImageButtonReleaseEvent);
		}
	}
}
